### ISSUE TITLE
Add support for bulk Database result methods

### ISSUE THREAD

**Issue by jamessimone** [jongpie/NebulaLogger#101]
We recently added options (#59)  to log `Database.SaveResult` and the other DML-based result classes, but these classes are most typically returned to the client in bulk (ie, `List<Database.SaveResult>`). For the times where the user just wants to create a log of all the results, we should expose bulk methods as well to better assist so that they don't have to iterate through each item in the collection manually.

**Comment by jongpie** [comment]
I really like this idea - while we're at it, I think it makes sense to do the same thing for `List<SObject>` as well. For both a list of SObject and a list of Database results, you'll lose some granularity on `LogEntry__c` (e.g., `LogEntry__c.RecordId__c` won't be set if a list of SObject or Database results is provided), but I think this will be a really convenient addition for developers.
