### ISSUE TITLE
Deployment with GH SF Deploy Tool Fails

### ISSUE THREAD

**Issue by aranwe** [jongpie/NebulaLogger#122]
Hi, 

When trying to deploy NebulaLogger with GH SF Deploy Tool I get following Failures:

```
Failures:
deploy/classes/LogHandler.cls(127,29):Illegal assignment from List to List
deploy/classes/LogHandler.cls(134,52):Method does not exist or incorrect signature: void getValue() from the type PicklistEntry
deploy/classes/LogHandler.cls(135,54):Method does not exist or incorrect signature: void getValue() from the type PicklistEntry
deploy/classes/LogHandler_Tests.cls(127,29):Dependent class is invalid and needs recompilation:
 Class LogHandler : Illegal assignment from List to List
deploy/triggers/Log.trigger(6,5):Invalid type: LogHandler
deploy/profiles/Admin.profile(Admin):In field: apexClass - no ApexClass named LogHandler found
```

Also the README.md button [Deploy Unpackaged Metadata] should use:
`https://githubsfdeploy.herokuapp.com?owner=jongpie&repo=NebulaLogger&ref=master`
(i.e. including the owner/repo/branch)

Cheers!

**Comment by jongpie** [comment]
@aranwe thanks for reporting this! Offhand, I'm not sure what would be causing this issue, but I'll do some analysis ASAP. Are you deploying it for the first time to your org? Or do you already have an old version deployed, and you're now deploying the latest version in `master`?

**Comment by aranwe** [comment]
@jongpie Thank you! First time & yes, from master.

**Comment by jongpie** [comment]
@aranwe when you have a chance, could you try running the deployment again? I've tested it in some new sandboxes, but I'm not able to reproduce the issue. Let me know if it's still happening for you!

**Comment by aranwe** [comment]
@jongpie haven't forgotten about this, I am just in the middle of larger release. I should be able to get to this later next week :) 
Thank you for you help btw!

**Comment by jongpie** [comment]
Hey @aranwe - I'm going to go ahead and close this issue since it's been open for a while and I haven't been able to reproduce it (and haven't heard from others having this issue). There is also now an unlocked package that you could use instead of deploying the metadata directly (see README for details).

**Comment by aranwe** [comment]
Hey @jongpie sure, sorry for not getting back to you, unfortunately other stuff in our org had priority, so I couldn't work on this :) 
I will try the unlocked package :) 

Cheers & thank you for the support :)

**Comment by jongpie** [comment]
@aranwe no worries at all! Just let me know if you run into any other issues!
