### ISSUE TITLE
StartTime__c off by one hour. 

### ISSUE THREAD

**Issue by KacperAugustyniak** [jongpie/NebulaLogger#132]
Hi,

We noticed that we have wrong start time in logs. We fixed it by changing this code. 
`this.logEntryEvent.TimestampString__c = String.valueOf(this.logEntryEvent.Timestamp__c);`
To 
`this.logEntryEvent.TimestampString__c = String.valueOf(this.logEntryEvent.Timestamp__c.getTime());`
And 
`Datetime.valueOf(logEntryEvent.TimestampString__c)`
To 
`Datetime.valueOf(Decimal.valueOf(logEntryEvent.TimestampString__c))` 

Cheers!

**Comment by jongpie** [comment]
Hi @KacperAugustyniak - I'm not able to reproduce this issue, the timestamps in my scratch org are being populated with the correct timestamps. Could you provide more details about how you're testing this? And what time zone is your user using?

**Comment by KacperAugustyniak** [comment]
Hi. All users use GMT+2 Central European summer time Berlin and we use `saveLog()` method. 
Almost all logs are generated by API user form another system through apex `@RestResource`.
Start time was always one hour ahead.

**Comment by KacperAugustyniak** [comment]
We use event messages to save logs. 

“Automated process” user have Dublin time zone for some reason. You should be able to replicate bug by setting user time zone to a time zone different than automated user’s time zone and save log using event bus. 

I would also like to note JSON.serialize and deserialize approach also produces correct time stamp.

**Comment by jongpie** [comment]
@KacperAugustyniak thanks for the details! I'm going to try to reproduce this issue this week - assuming I can get it reproduced, then I'll look into updating the code with your suggestions. I'll let you know if I need any other information, thanks again!

**Comment by jongpie** [comment]
@KacperAugustyniak I've fixed this issue in PR #153 - it's been merged to the `main` branch and is also available in the unlocked package [release v4.4.4](https://github.com/jongpie/NebulaLogger/releases/tag/v4.4.4). Let me know if you find any other bugs!
