### ISSUE TITLE
List to object assignment error - Organization

### ISSUE THREAD

**Issue by itsikra** [jongpie/NebulaLogger#136]
Unmanaged package installation fails with following error:
deploy/classes/LogHandler_Tests.cls(47,22):Illegal assignment from List to Organization

which cascades into other errors as well. 

Relevant code:
Organization organization = [SELECT Id, InstanceName, IsSandbox FROM Organization];

Trying this from developer console generates the error: 
Illegal assignment from List<Organization> to Organization

Even when wrapping results as a list: 
Illegal assignment from List<Organization> to List<Organization>

Cause:
=====
Salesforce has both an Apex class named "Organization" as well as an SObject (custom object) named "Organization". 

Refs: 
====
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Organization_static_methods.htm
https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_organization.htm

Solution:
======
Code in the above mentioned test file, also in getOrganization() method from LogEntryEventBuilder.cls and in any other "Organization" query, should be specifying the exact object expected from the query: (a schema object)

LogHandler_Tests.cls:
Schema.Organization organization = [SELECT Id, InstanceName, IsSandbox FROM Organization];    ..........

LogEntryEventBuilder.cls:
private static final Schema.Organization ORGANIZATION = getOrganization();   ..........
private static Schema.Organization getOrganization() {   ..........

Thank you for your hard work.

**Comment by jongpie** [comment]
Hi @itsikra - thanks for reporting this! Based on the error message, it sounds like the query `[SELECT Id, InstanceName, IsSandbox FROM Organization]` is returning multiple results (`List<Organization>`) instead of a single instance of `Organization`. Can you confirm how many results you get in your org when running the query `SELECT Id, InstanceName, IsSandbox FROM Organization`?

**Comment by itsikra** [comment]
Of course, tested all possible scenarios, and I do have 1 "Organization" result.
You are correct though, best practice IS to return query results into a list in case there are several results, and just perform a list.get(0) when expecting a single result.

As I mentioned, I have also tried returning the results into a list, without success. Here is the irrational error message returned:
![image](https://user-images.githubusercontent.com/24872765/116290645-5e136c00-a79c-11eb-9b0b-43eec091c636.png)


It only succeeds when I assign the result into a Schema.Organization object, which is the actual object(s) you are expecting to return from the query. 
When you declare "Organization" alone, you get an instance of a whole other apex class.

Not your fault of course. Salesforce shouldn't have named 2 different objects with the same name.

Thank you.

**Comment by jongpie** [comment]
Perfect, thanks for the details @itsikra! I'm not sure why this error is just now happening (I've been using some of this code for years without any issues), but it seems like a fairly straightforward fix - I'll try to get this fixed within the next few days.

**Comment by jongpie** [comment]
@itsikra one more question on this - any chance your org has a custom Apex class called `Organization`? The only way to use [the standard Apex class you mentioned](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_ConnectAPI_Organization_static_methods.htm) is if you include the `ConnectAPI` - e.g., `ConnectApi.Organization`, so I don't think it's an issue with the query trying to be assigned to an instance of `ConnectApi.Organization`. And in your original message, you said that running this code below in dev console results in the same error, but I've tested this in 4 different sandbox orgs and a scratch org without any issues
```java
// Running this query in dev console and the logger code works for me - I'm unable to reproduce your error
Organization organization = [SELECT Id, InstanceName, IsSandbox FROM Organization];
```

**Comment by itsikra** [comment]
@jongpie Nice catch! It does require the ConnectAPI namespace. 

I had previously searched entire code base and no such class named Organization was found. 
So I had to perform a thorough check in the sandbox just to reveal a class named "Organization" that is not used by the dev team. 

Thanks for your help!

**Comment by jongpie** [comment]
Awesome, glad to hear you found the issue! Since it was an issue just in your org, I'm going to close this issue, but let me know if you run into any other problems!
