### ISSUE TITLE
Missing layout file

### ISSUE THREAD

**Issue by itsikra** [jongpie/NebulaLogger#138]
Hi @jongpie 
Unmanaged package installation fails with the following message: 

![image](https://user-images.githubusercontent.com/24872765/116435959-96768100-a854-11eb-9429-f489d05c72b6.png)

Please advise whether there is a file missing in the "layouts" folder. 

Thank you

**Comment by jongpie** [comment]
@itsikra that reference actually shouldn't be in the repo at all, it looks like I accidentally committed that section of the Admin profile. I'll have that fixed ASAP!

**Comment by itsikra** [comment]
@jongpie 
Lightning quick! Thanks!

**Comment by jongpie** [comment]
@itsikra this should be working now! I've merged PR #139 to remove the extra Account references within the Admin profile
