### ISSUE TITLE
Unlocked Package

### ISSUE THREAD

**Issue by surajp** [jongpie/NebulaLogger#143]
I find unlocked packages to be a happy medium between ease of installation and upgrades, and overcoming some of the limitations of managed packages ( such as the one with `System.debug` and the inability to access public methods). Having that option for NebulaLogger would be nice

**Comment by jongpie** [comment]
@surajp the unlocked package has officially been released in [v4.4.1](https://github.com/jongpie/NebulaLogger/releases/tag/v4.4.1)! I've also updated README with details about using the unlocked package vs the managed package

**Comment by surajp** [comment]
thanks @jongpie ! Much appreciated.
