### ISSUE TITLE
Logging as Guest User Fails

### ISSUE THREAD

**Issue by mykah89** [jongpie/NebulaLogger#145]
Apologies in advance, I'm relatively new to Salesforce development, I recently began using the logger successfully but I think I may have quickly come across an edge case.

Perhaps an obscure requirement but I'm looking to log from a public site with a @RestResource endpoint, I'm getting the following error when I trace the Automated Process user.

field integrity exception (Guest users cannot be record owners.)

It makes sense as to why I'm getting the error, but I was wondering if there was any work around here?

**Comment by mykah89** [comment]
Wanted to quickly follow up on this that I was able to get around this for now replacing the line that sets the log.OwnerId in the LogEntryEventHandler class, obviously this is not ideal if I need to update the Nebula logger, but it will allow me to continue with my use case.

In case anyone is curious I just added an additional custom setting checking for the profile name which was already available from the logEntryEvent.ProfileName__c, and then defaulting back to the Autoprocess User as owner if not.

log.OwnerId = Extended_Logger_Settings__c.getValues('Extended Logger Settings').Guest_Profile_Names__c.Contains(logEntryEvent.ProfileName__c) ? System.UserInfo.getUserId() : logEntryEvent.CreatedById;

Coincidentally about 4 lines below this line of code the log's SessionId is set twice.

            log.SessionId__c = logEntryEvent.SessionId__c;
            log.SessionId__c = logEntryEvent.SessionId__c;


I would still very much appreciate an alternative work around that may be more suitable if one exists.

**Comment by jongpie** [comment]
Hi @mykah89 thanks for reporting this! I think your workaround of setting the record owner to the 'Automation Process' user (instead of the guest user) makes sense/seems like a great solution - I'll try to fix this sometime within the next few weeks.

**Comment by jongpie** [comment]
@mykah89 I've merged a fix for this to the `main` branch - there is now also an unlocked package that you can use, the latest [release v4.4.3](https://github.com/jongpie/NebulaLogger/releases/tag/v4.4.3) contains this bugfix.

Let me know if you have any other issues!

**Comment by mykah89** [comment]
This is great, much appreciated, I had to refactor some of the calls I was using that used Topics, but other than that I was able to install the Unlocked Package right over the deployed metadata without issue.

Thanks again.

**Comment by jongpie** [comment]
@mykah89 glad you were able to successfully switch to the unlocked package! And I'm hoping to spend some more time expanding the functionality for Topics - hopefully within the next few weeks.
