### ISSUE TITLE
Topic creation failure with spaces as differentiator

### ISSUE THREAD

**Issue by mykah89** [jongpie/NebulaLogger#154]
I know this is a little late to the party since you pulled out the public Topic methods for redesign, however, perhaps it can save you or someone else some pain down the road.

I was using Topics (successfully), and since you left the setTopics in the LogEntryEventBuilder I will continue using them as I was. with the Unlocked package.

I stumbled on this when I was doing some refactoring, I removed a space from one of the Topics I was using and then I was not getting any topics on my log entry outputs.

It appears that inserting topics with only spaces as a differentiator in the name causes a DML DUPLICATE_VALUE exception.

Since, the logic to look up the Topics by name returns no results for the 'spaced' version it is considered new and subsequently an exception is thrown when it attempts the insert.

**Comment by jongpie** [comment]
Hi @mykah89, you can definitely continue to use the method `LogEntryEventBuilder.setTopics()` - I had to remove the topics-related methods in the `Logger` class to help with overall maintenance (the class was huge and there were dozens of overloads), but I am planning to keep the method `LogEntryEventBuilder.setTopics()` and will be adding some other topics-related functionality in the next few releases.

Just to help make sure I understand this issue, could you provide some sample code that demonstrates the problem?

**Comment by mykah89** [comment]
Makes sense.

Sure, the following code will not succeed, pulled more or less from the insertTopics function of the LogEntryEventHandler.cls

`
private static void createTopics(string topicString) {
	Set<String> topicNames = new Set<string>();

	topicNames.addAll(topicString.split(','));

	Map<String, Topic> topicNameToTopics = new Map<String, Topic>();
	for (Topic topic : [SELECT Id, Name FROM Topic WHERE Name IN :topicNames]) {
		topicNameToTopics.put(topic.Name, topic);
	}

	List<Topic> topicsToCreate = new List<Topic>();
	for (String topicName : topicNames) {
		if (topicNameToTopics.get(topicName) != null) {
			continue;
		}
		topicsToCreate.add(new Topic(Name = topicName));
	}

    if (!topicsToCreate.isEmpty()) {
        insert topicsToCreate;
    }
}

createTopics('Test Space');

createTopics('TestSpace');
`

**Comment by jongpie** [comment]
Thanks @mykah89, that's really helpful! I'll include a bugfix for this issue when I work on some of the other Topics enhancements.
