### ISSUE TITLE
System.CalloutException in tests

### ISSUE THREAD

**Issue by itsikra** [jongpie/NebulaLogger#159]
Hi @jongpie 

We are experiencing System.CalloutException exceptions during tests, for same flows that work fine in regular deployment with the logger.
Problem occurs only when using the logger and only when running tests.
We are aware of the salesforce DML-Callout issue.

Do you have any past experience/insights/solution for this? 

Thanks

**Comment by jongpie** [comment]
Hi @itsikra - could you provide some more details about this issue?

1. Which version of the tool are you using? (3 options: unpackaged metadata, unlocked package, or managed package)
2. Can you provide the full error/stacktrace from the test failure?
3. What Salesforce DML-callout issue in particular are you referring to?
4. Are you only using the logger within Flows?

Thanks!

**Comment by itsikra** [comment]
The version installed is the managed package.
We get failure with message: 
_Error: System.CalloutException: You have uncommitted work pending. Please commit or rollback before calling out_

We only use the logger in backend code. I meant the tests are true to the original flow of the code. 
The logger works great, in every scenario of our storefront. 

The Salesforce issue meaning Salesforce do not allow DML operations before callouts in a single transaction. However, same code flow works when running from the store. The failures only occur in the tests. 

Thank you

**Comment by jongpie** [comment]
@itsikra thanks for the details - within your org, are you specifically using the callout functionality of the `Logger` class? For example, are you calling `Logger.saveLog(Logger.SaveMethod.REST)` or configuring the custom setting `LoggerSettings__c.DefaultSaveMethod__c = 'REST'`? By default, it doesn't use the REST API, so I'm not 100% sure why callout errors are happening (unless your explicitly using the REST callouts). 

If you're able to provide any more details (such as sample code of how you're using the logger when it fails in tests, the test's error or stacktrace, etc),  that'd be helpful.

**Comment by itsikra** [comment]
Have edited my previous reply. 
We are always saving the logs using Nebula.Logger.saveLog()
Didn't realize saveLog() can take parameters. Is there any documentation on that? 

Thanks

**Comment by jongpie** [comment]
Ah, ok - since you're making callouts within your code, you may actually need to consider leveraging the parameters for `saveLog()`. There's a [GitHub.io site](https://jongpie.github.io/NebulaLogger/) for the project that has details for all of the Apex classes, [including Logger](https://jongpie.github.io/NebulaLogger/logger-engine/Logger), but I need to also include some details within the README too. I'll work on updating the repo's README with more info, but here's some relevant details for your issue:
-   `Logger.saveLog(SaveMethod saveMethod)` - saves any entries in Logger's buffer, using the specified save method for only this call. All subsequent calls to `saveLog()` will use the default save method. There are currently 3 supported save methods:
    1. `Logger.SaveMethod.EVENT_BUS` - The default save method, this uses the `EventBus` class to publish `LogEntryEvent__e` records. Using the `EventBus` does count towards the current transaction's DML usage
    2.   `Logger.SaveMethod.QUEUEABLE` - This save method will trigger `Logger` to save any pending records asynchronously using a queueable job. This is useful when you need to defer some CPU usage and other limits consumed by `Logger`
    3.   `Logger.SaveMethod.REST` - This save method will use the current user’s session ID to make a synchronous callout to the org’s REST API. This is useful when you have other callouts being made and you need to avoid mixed DML operations
 
Without seeing any of your code, it's hard to say why you're only seeing this issue within your tests - but you can try using either the `QUEUEABLE` or `REST` save methods to help avoid the `CalloutException`.

**Comment by shahartal80** [comment]
> Ah, ok - since you're making callouts within your code, you may actually need to consider leveraging the parameters for `saveLog()`. There's a [GitHub.io site](https://jongpie.github.io/NebulaLogger/) for the project that has details for all of the Apex classes, [including Logger](https://jongpie.github.io/NebulaLogger/logger-engine/Logger), but I need to also include some details within the README too. I'll work on updating the repo's README with more info, but here's some relevant details for your issue:
> 
> * `Logger.saveLog(SaveMethod saveMethod)` - saves any entries in Logger's buffer, using the specified save method for only this call. All subsequent calls to `saveLog()` will use the default save method. There are currently 3 supported save methods:
>   
>   1. `Logger.SaveMethod.EVENT_BUS` - The default save method, this uses the `EventBus` class to publish `LogEntryEvent__e` records. Using the `EventBus` does count towards the current transaction's DML usage
>   2. `Logger.SaveMethod.QUEUEABLE` - This save method will trigger `Logger` to save any pending records asynchronously using a queueable job. This is useful when you need to defer some CPU usage and other limits consumed by `Logger`
>   3. `Logger.SaveMethod.REST` - This save method will use the current user’s session ID to make a synchronous callout to the org’s REST API. This is useful when you have other callouts being made and you need to avoid mixed DML operations
> 
> Without seeing any of your code, it's hard to say why you're only seeing this issue within your tests - but you can try using either the `QUEUEABLE` or `REST` save methods to help avoid the `CalloutException`.

Hi @jongpie - Thanks for your detailed response. I work with @itsikra . The default saveMethod using EventBus using the publish immediate method, which is also there by default should not have counted against the current transaction DML usage as far as I understand. Here's a relevant article. https://help.salesforce.com/articleView?id=release-notes.rn_platform_events_publish_immediate_limit.htm&release=228&type=5 . I'm still puzzled why this only happens in test classes.

**Comment by itsikra** [comment]
Thanks @jongpie 

Your last suggestion did solve the issue. 
However, this worked only for the unmanaged package installation. 
For the managed package, the LoggerSettings__c is not recognized at all via code or DML(Apex, developer console, cannot even query it in the query editor). 

Any idea why? Is this salesforce limitation relevant? (Protected access level?)
_If Privacy for a custom setting is Protected and the custom setting is contained in a managed package, the subscribing organization can’t edit the values or access them using Apex._
(link: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_customsettings.htm)

Thank you

**Comment by jongpie** [comment]
Hey @itsikra - for the managed package, you'll have to include the namespace. Try accessing/updating it using `Nebula__LoggerSettings__c`

**Comment by itsikra** [comment]
Of course...
Thanks @jongpie for all your help, the LoggerSettings upsert finally resolved the issue. 

Itsik

**Comment by jongpie** [comment]
@itsikra glad to hear that solved it! I'm going to go ahead and close this issue, but let me know if you need anything else!
