### ISSUE TITLE
Add the ability to extend the SObject handler classes

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#164]
There should be a way (at least in Apex - potentially Flow as well) to run additional logic in the `LogHandler`, `LogEntryHandler` and `LogEntryEventHandler` classes without having to modify these classes directly.

- Each handler class should manage running any extra logic for its SObject Type
- Developers should be able to write their own Apex classes to further manipulate the logging records in `Log__c` and `LogEntry__c`, `LogEntryEvent__e`

**Comment by jamessimone** [comment]
This is implied, but to make it explicit - all defined handlers should run _after_ the base logging handlers so that they can hook into all fields updated before insert/update
