### ISSUE TITLE
LogBatchPurger Too many DML rows: 10001

### ISSUE THREAD

**Issue by starkguerraj** [jongpie/NebulaLogger#166]
Getting this error for a batch whenever LogBatchPurger runs.

Almost latest version 4.4.5 of the Unlocked Package.

Will try to get some more details.

**Comment by starkguerraj** [comment]
Here is a snippet of the exception from the debug log.

![image](https://user-images.githubusercontent.com/72459978/120896100-fdbee800-c5ed-11eb-9237-e92ab6a5fd7b.png)

**Comment by jongpie** [comment]
Hey @starkguerraj - I'll have to work on optimizing that batch job, but as a quick workaround, you can try re-running the batch job with a smaller batch size (the default is 200). Try running this Apex script to see if it'll successfully delete your records:
```java
Integer batchSize = 100;
Database.executeBatch(new LogBatchPurger(), batchSize);
```

**Comment by starkguerraj** [comment]
Definitely will do that for now, I tried 10 then moved down to 1 to finish off a few that were failing.

Thanks

**Comment by jamessimone** [comment]
@starkguerraj I went ahead and took care of this one for you - @jongpie will be releasing Version `4.5.0` later this week with the updates from this and from #165. Let us know if there are any further issues!

**Comment by starkguerraj** [comment]
You guys are great, I really appreciate it.

**Comment by jongpie** [comment]
@starkguerraj I was a little slow in release version `4.5.0`, but it's now finally live!
- [Unlocked package v4.5.0](https://nebula-pkg-demo-dev-ed.my.salesforce.com/packaging/installPackage.apexp?p0=04t5Y0000027FMrQAM)
- [Managed package v4.5.0](https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5Y0000027FMhQAM)

Let us know if you run into any other issues!

**Comment by starkguerraj** [comment]
Thanks for the update, I was able to get the package installed, bad new unfortunately, received an exception this morning, here is the stack trace from the email, let me know if there's anything else I can provide.

Failed to process batch for class 'LogBatchPurger' for job id '7073Z0000DQd275'

caused by: System.LimitException: Too many DML rows: 10001

Class.LogBatchPurger.LogDeleter.hardDelete: line 65, column 1
Class.LogBatchPurger.LogDeleter.process: line 47, column 1
Class.LogBatchPurger.execute: line 102, column 1

**Comment by jongpie** [comment]
@starkguerraj, darn, I thought we had this resolved! Sorry for the ongoing issues! I think there are a couple of next steps:

- For now, you can keep specifying a batch size ([as mentioned above](https://github.com/jongpie/NebulaLogger/issues/166#issuecomment-855348619)) until we get yet another release out for this
- We'll look into further optimizing the code again to better handle that `Too many DML rows` error
- I'm considering also adding another constructor to [LogBatchPurgeScheduler](https://github.com/jongpie/NebulaLogger/blob/main/nebula-logger/main/log-management/classes/LogBatchPurgeScheduler.cls) with a parameter `Integer batchSize` - this would let you specify the batch size for the scheduled job. The only downside is that you'd have to schedule the job via Apex, not the Salesforce UI, but it would give admins more control over the scheduled job

**Comment by starkguerraj** [comment]
@jongpie

No big deal, just wanted to keep it on the radar.

The last option seems like a great interim solution with a low amount of development effort for something that may be an edge case issue (me).

**Comment by jongpie** [comment]
Sounds good, I'll plan to add the extra constructor in the next release (as well as some other optimizations for the actual deletion process) - I've reopened this issue too.

**Comment by jongpie** [comment]
@starkguerraj the newest release, [v4.6.0](https://github.com/jongpie/NebulaLogger/releases/tag/v4.6.0), has 2 related changes:

- `LogBatchPurgeScheduler` has a new constructor, `LogBatchPurgeScheduler (Integer batchSize)`. This can be used to specify the batch size used when executing  `LogBatchPurger`
  ```java
    String cronExpression = '0 0 23 * * ?';
    Integer batchSize = 100;
    System.schedule('LogBatchPurgeScheduler with custom batch size', cronExpression, new LogBatchPurgeScheduler(batchSize));
  ```
- `LogBatchPurger` has been optimized - my hope is that you'll no longer run into issues like 'Too many DML rows' or 'Apex CPU time limit exceeded' (mentioned in #176)

**Comment by starkguerraj** [comment]
I was finally able to update my sandbox org from 4.5 to the latest unlocked 4.6.9.

Unfortunately there is a new error now, I attempted to execute the purger to test as follows, Database.executebatch(new LogBatchPurger(), 1).

It doesn't appear I'm over the limits as the error may suggest so perhaps its an internal issue, please let me know if there's something else I can provide to help you track this down. 

![image](https://user-images.githubusercontent.com/72459978/136385386-a14a5c3f-8286-4edd-afef-35759df71183.png)

![image](https://user-images.githubusercontent.com/72459978/136385546-ba62c9ca-ca30-4117-86fb-0ff07b65fa90.png)


![image](https://user-images.githubusercontent.com/72459978/136385528-5758cdc9-19a9-4bad-a1a8-fdfcca3b1b10.png)

**Comment by starkguerraj** [comment]
I see, looking at the commit history

* Switched to new approach in LogBatchPurger - it now runs separate batch jobs for each of Logger's objects

So running with a batch size of 1 is more likely no longer appropriate.

![image](https://user-images.githubusercontent.com/72459978/136457001-ec3ce5b9-ee33-4bdd-867a-8de94d7d2947.png)

Would you happen to have a recommendation on a setting size?

Thanks

**Comment by starkguerraj** [comment]
Thanks for the update and explanation.

Prior to your response I arbitrarily picked 10000 to see what would happen and it appeared to execute without issue.

On a side note, it looks like there may be a separate issue now, there looks to be a bunch of Log records with no Entries and no start times that are well beyond my retention date that were not deleted.

![image](https://user-images.githubusercontent.com/72459978/136551431-8b5413ac-f737-4dec-b79c-2645cc718d06.png)

**Comment by jongpie** [comment]
@starkguerraj that's awesome that it worked for such a large batch size (I _think_ that it probably used a batch size of 2,000, even though you specified 10,000, since 2,000 is the max). This really helps confirm that the optimizations/new approach have helped - thanks for confirming that!

As far as those strange log records, it could be 1 of 2 scenarios:

1. Occasionally, there are bugs in Logger that cause the creation of `LogEntry__c` records to fail, but the `Log__c` records are still created. This has happened some in the past due to bugs like "a required field on `LogEntry__c` wasn't being populated", or "a field value on `LogEntry__c` exceeded the field's max length", etc. So these could be some older logs in your org that were impacted by one of these bugs.
2. It very well could be due to a bug within the `LogBatchPurger` job - there might have been related `LogEntry__c` records that were successfully deleted, but for whatever reason, the deletion batch job failed to delete the `Log__c` records.

In both of these 2 scenarios, the end result would look exactly like your screenshot - `Log__c` records with 0 related log entries - so it's hard to say which scenario you're seeing there. Could you check if the `Log__c` records in your screenshot have a value for the field `Log__c.RetentionDate__c`? If that field is null, then I think it's probably scenario 1 - if it's not null, then it probably is in fact another bug in the batch deletion job.

**Comment by starkguerraj** [comment]
They definitely have helped, thanks for that.

There is a retention date, some a few months old and some as recent as today (post logger upgrade), so I'm not sure which situation would have applied.

It does sound like deleting logs with no entry records would resolve the issue, and I cant really see a good reason to keep Logs without any entries.
