### ISSUE TITLE
Get "INVALID_FIELD, Foreign key external ID: .... not found for field TransactionId__c" when 

### ISSUE THREAD

**Issue by isidle** [jongpie/NebulaLogger#174]
When using `setParentLogTransactionId(logger.getTransactionId());` to assign a value equivalent to the current id, the DML operation fails...

The receiving method should be adjusted so it only passes the value downstream if the value is different than the current session.

**Comment by jongpie** [comment]
Hi @isidle - just to help me better understand your use case, what's the reason that you're passing the current transaction ID as the parent log's transaction ID? I can definitely look into handling that scenario within the code, but it's not really a valid scenario in the first place - `Logger.setParentLogTransactionId(Logger.getTransactionId());` will never work, so it sounds strange that you're using that code in your org.

**Comment by isidle** [comment]
@jongpie I'm setting Logger.getTransactionId() to a static variable and then have a Queueable method that will fire 1 or more times, depending on the size of the request & remaining limits. 

If the loop get's to a system limit, it would fire a subsequent "batch" with the remaining items. 

Say for example, I need to update 100,000 records. 
The first execution will update 10,000  records and then fires a new copy of itself, with the 90,000 remaining items which updates the next 10,000 and continues recursively until the list is empty (executing a total of 10 times in this example). 

If setup correctly, the same logic can be used without needing to maintain two set's of code (first run and subsequent runs). 

I suppose I could add an extra if statement to figure out which loop it is in and pass the value is empty, but IMO that is a workaround as I think the method should be able to more gracefully handle this situation. 

If out of principle you think this shouldn't be permitted and should generate an error, then the method should throw an exception with something like "Can't pass current TransactionId into setParentLogTransactionId" rather than waiting until the Log__c DML to fail which generates a message that doesn't describe what needs to be changed.

**Comment by jongpie** [comment]
@isidle thanks so much for the explanation - that makes a lot of sense, and you've convinced me about the proposed change. Your scenario is definitely a common scenario for anyone logging in queueable/batchable jobs, and I love the idea of "the same logic can be used without needing to maintain two set's of code (first run and subsequent runs)".

I'll put together a small PR so that `Logger.setParentLogTransactionId()` will ignore the parent ID value if the provided parent ID == the current transaction ID. Thanks again!

**Comment by jongpie** [comment]
@isidle I think I've got all of the code changes completed in PR #175 - I just need to create a new package version for the unlocked package. Unfortunately my laptop died last night, so it'll take me a few days before I'll be able to release the new package version.

In the meantime, let me know if you find any other issues!

**Comment by jongpie** [comment]
@isidle the newest release, [v4.6.0](https://github.com/jongpie/NebulaLogger/releases/tag/v4.6.0), contains this change. Let me know if you run into any issues or have any other feedback!
