### ISSUE TITLE
LogBatchPurger - Apex CPU time limit exceeded

### ISSUE THREAD

**Issue by starkguerraj** [jongpie/NebulaLogger#176]
Having issues with the LogBatchPurger, admittedly I'm logging a lot of things.

Looking into the class, the start method is also querying for the Id from LogEntries__r relationship, but it appears to be unused.

Removing this part from the start function seems to resolve this issue for me and as far as I can tell does not affect the process.

Can you advise on anything I'm overlooking and a reason why this would be a bad idea?

Thanks

**Comment by jongpie** [comment]
Hi @starkguerraj, thanks for reporting this! There have been a couple of performance issues with that job that we've been trying to resolve (see #146 and  #166). I think your changes are perfectly fine for now - I am working on some additional changes to that batch job as part of PR #173 to try to make some other optimizations. 

Just out of curiosity, when the CPU time limit is exceeded, do you know approximately how many `LogEntry__c` records are being returned in your org for the `LogEntries__r` relationship?

**Comment by starkguerraj** [comment]
Sure, thanks for responding.

I'm not sure how many LogEntry__c records are being returned in the relationship but this job has been failing for some days maybe a couple weeks now, I can tell you that I have many Logs with up to 5k Log Entries if that helps at all, if there is an easy way to check for you let me know.

**Comment by jongpie** [comment]
@starkguerraj one way you could check in your org is to run one of these queries (depending on if you're using the unlocked package or the managed package). If that's feasible, and you don't mind sharing the results, this would be helpful in resolving the issue.

Unlocked package version of query
```java
SELECT MAX(TotalLogEntries__c) maxCount, AVG(TotalLogEntries__c) avgCount FROM Log__c
```

Managed package version of query
```java
SELECT MAX(Nebula__TotalLogEntries__c) maxCount, AVG(Nebula__TotalLogEntries__c) avgCount FROM Nebula__Log__c
```

**Comment by starkguerraj** [comment]
Yea no problem.



Running that query from an anonymous apex in vscode for the unlocked package version.

14:27:23.22 (371819729)|EXCEPTION_THROWN|[12]|System.LimitException: Too many query rows: 50001
14:27:23.22 (372268305)|FATAL_ERROR|System.LimitException: Too many query rows: 50001

  Number of SOQL queries: 1 out of 100
  Number of query rows: 95952 out of 50000 ******* CLOSE TO LIMIT
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 0 out of 150
  Number of Publish Immediate DML: 0 out of 150
  Number of DML rows: 0 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10


From my full sandbox which had done more logging and been failing for a bit longer.

  Number of SOQL queries: 1 out of 100
  Number of query rows: 179290 out of 50000 ******* CLOSE TO LIMIT
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 0 out of 150
  Number of Publish Immediate DML: 0 out of 150
  Number of DML rows: 0 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

Not sure if this helps, but if I can provide anything else, let me know.

**Comment by jongpie** [comment]
@starkguerraj apologies, it looks like my previous query is running into SOQL limits in your org - could you try running this query instead?

```java
SELECT Log__c, COUNT(Id) 
FROM LogEntry__c
GROUP BY Log__c
ORDER BY COUNT(Id) DESC
LIMIT 10

```

**Comment by starkguerraj** [comment]
No issue, here is the output from my production org, let me know if I can get anything else to assist.

16:41:20.721 (2721779122)|USER_DEBUG|[22]|DEBUG|(AggregateResult:{Log__c=a6K3Z000000WGzbUAG, expr0=5022}, AggregateResult:{Log__c=a6K3Z000000W5j2UAC, expr0=5022}, AggregateResult:{Log__c=a6K3Z000000WTn2UAG, expr0=5014}, AggregateResult:{Log__c=a6K3Z000000W6ZYUA0, expr0=4976}, AggregateResult:{Log__c=a6K3Z000000WHPbUAO, expr0=4976}, AggregateResult:{Log__c=a6K3Z000000WTmtUAG, expr0=4876}, AggregateResult:{Log__c=a6K3Z000000WIaHUAW, expr0=4876}, AggregateResult:{Log__c=a6K3Z000000WToNUAW, expr0=4830}, AggregateResult:{Log__c=a6K3Z000000WTnAUAW, expr0=4784}, AggregateResult:{Log__c=a6K3Z000000WGcRUAW, expr0=4784})

**Comment by jongpie** [comment]
Thanks @starkguerraj - that's all I need for now, just wanted to confirm how big some of your logs are. To be honest, I've never seen that many `LogEntry__c` records related to a single `Log__c` record, but it's fascinating & great to know that it's working in your org. 

I'll be spending some time next week on PR #173 - I'll do some additional testing with similar data to make sure that large `Log__c` records are successfully deleted by the batch job

**Comment by starkguerraj** [comment]
Sure, no problem.

It is definitely working well, these are some logs from some large changes syncing over and running in a batch from an external system. 

I am utilizing debug level at the moment as well so they will definitely become smaller in the future, but I'm glad I can test out the limits of some stuff in the meantime.

**Comment by jongpie** [comment]
@starkguerraj the newest release, [v4.6.0](https://github.com/jongpie/NebulaLogger/releases/tag/v4.6.0), has some optimizations for the `LogBatchPurger` job. If/when you upgrade, let me know if you still have any more issues!
