### ISSUE TITLE
Use platform cache for storing unsaved log entries

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#18]

**Comment by jongpie** [comment]
I'm not 100% sure that this would actually improve performance - this needs to be further researched to confirm if it would actually provide any performance improvements.

**Comment by jamessimone** [comment]
@jongpie while we don't know how the Log entries are impacting heap size, one thing we could do is push uncommitted log entries to the platform cache in the event that `Limits. getHeapSize()` is approaching `Limits.getLimitHeapSize()`, and the number of logs is over some sentinel number (or sentinel feature enabled, like storing the record as JSON is enabled; something that indicates to us "we might be contributing significantly to the rapidly dwindling allowable heap usage).

Then we can either dispatch a platform event or queueable to handle extracting the entries from the cache and committing them.

Just some thoughts after you left your comment ...

**Comment by jongpie** [comment]
@jamessimone I had one other _possible_ use case for platform cache. 
- **Issue**: Right now, in a "normal" situation, `Logger` uses `EventBus.publish()` for creating `LogEntryEvent__e` records - but if there is an issue publishing the events, then those events might never get saved. 
  - I know this can happen if you exceed the daily limit of events you can publish (yeah, there's a limit for that too... and yes, I _did_  hit the limit once...). There might be other situations where the events fail to publish, but this limit can definitely cause failures.
- **Possible Solution**: Use platform cache as a place to store and retry failed events that can't be saved in the current transaction.  Somewhere in the codebase, it would then occasionally check the platform cache for these "failed & unsaved events" and try to publish them again.

Thoughts?

**Comment by jamessimone** [comment]
@jongpie https://help.salesforce.com/articleView?id=release-notes.rn_apex_freeplatformcache.htm&release=230&type=5 - just remembering this is also something we can just get "for free" after spring 21 comes out, all managed packages get 3mb of platform cache space!

**Comment by jongpie** [comment]
That'll be pretty nice - I'm still not 100% sure that using platform cache will be worth it for logger, but definitely worth looking into more.

**Comment by jongpie** [comment]
I'm going to go ahead and close this/tag it as `wontfix` for now - since not all orgs using the unmanaged version will platform cache, I don't want to build anything (yet) that leverages it.
