### ISSUE TITLE
Running into internal server error after calling Logger.saveLog()

### ISSUE THREAD

**Issue by emon-ampion** [jongpie/NebulaLogger#189]
I have followed all the right steps to install the (unlocked) package but getting this error when I try to use it in my apex code. Here's the error I am getting (I am on API 53):
```
An internal server error has occurred
Error ID: 280532468-82394 (239162002)
```

**Comment by jongpie** [comment]
Glad to hear it's working now - it does sound like an internal error, but let me know if you have any more issues!
