### ISSUE TITLE
Two Apex tests failing when more than one Apex class named "Logger" is present

### ISSUE THREAD

**Issue by csorrows-sysdig** [jongpie/NebulaLogger#204]
I just started evaluating Nebula Logger in our sandbox, and saw a couple Apex test failures I thought you might want to know about.  The class and methods failing are:

Class: LogEntryHandler_Tests
Method: it_should_set_apex_class_details_for_top_level_class (line 299)
Method: it_should_set_apex_class_details_for_inner_class (line 335)

Both lines perform the same query, where "exampleTopLevelClassName" is set to "Logger":

`ApexClass apexClass = [SELECT Id, ApiVersion, CreatedDate, LastModifiedDate FROM ApexClass WHERE Name = :exampleTopLevelClassName];`

These lines fail with "System.QueryException: List has more than 1 row for assignment to SObject" if the org has more than one Apex class named "Logger".  Our org has a managed package installed that also has an Apex class named "Logger", so the query returns two records which cannot be assigned to the single SObject.

It looks like the example "Logger" class it's trying to query is Nebula's own class, so maybe the WHERE clause could be extended to restrict it to one record, such as:

`ApexClass apexClass = [SELECT Id, ApiVersion, CreatedDate, LastModifiedDate FROM ApexClass WHERE Name = :exampleTopLevelClassName AND (NamespacePrefix = NULL OR NamespacePrefix = 'Nebula')];`

That would allow for selecting just Nebula's own Logger class, whether Nebula is installed as an unlocked or managed package.

Anyway, just a thought on a possible fix.

Lastly, I just wanted to give everyone working on this project a huge **THANKS!**  The home-grown logging system I created for our org has hit a limit on its usefulness for troubleshooting more complex logic, and I was faced with either putting a lot of time into enhancing it, or looking for a new logging framework when I ran across Nebula Logger.  The amount of functionality and quality you all have put into Nebula Logger is amazing, and it's greatly appreciated!

**Comment by jongpie** [comment]
Hey @csorrows-sysdig - that's a great find, thanks for reporting this issue! I had not even considered that scenario of another managed package also containing a `Logger` class, and I think your approach sounds like a great way to fix this. I'll work on releasing a new package version (hopefully) this week with this issue resolved.

And I'm thrilled to hear that you're enjoying Nebula Logger! @jamessimone and I have put a ton of work into it, especially over the last 9-12 months, with the goal of trying to make it the most robust logger for Salesforce. Glad that it's been useful for you - let us know if you have any other feedback for other bugs or possible enhancements! Thanks again!

**Comment by jongpie** [comment]
@csorrows-sysdig I've fixed these 2 problematic tests in the latest release, [v4.6.8](https://github.com/jongpie/NebulaLogger/releases/tag/v4.6.8). Thanks again for reporting this!
