### ISSUE TITLE
LoggerSettings creation fails as part of a wire function call

### ISSUE THREAD

**Issue by arbokrad** [jongpie/NebulaLogger#205]
When we installed the unlocked version of Nebula, we ran into an error with the following logs:

```14:46:47.0 (9447626)|USER_DEBUG|[45]|INFO|Logger.getTransactionId() == TID:2829900000cbb11d28
14:46:47.0 (10466217)|DML_BEGIN|[2645]|Op:Insert|Type:LoggerSettings__c|Rows:1
14:46:47.0 (10580196)|EXCEPTION_THROWN|[2645]|System.LimitException: Too many DML statements: 1
14:46:47.0 (10880657)|SYSTEM_MODE_EXIT|false
14:46:47.0 (10997450)|SYSTEM_MODE_EXIT|true
14:46:47.0 (11127246)|FATAL_ERROR|System.LimitException: Too many DML statements: 1

Class.Logger.setupOrgDefaults: line 2645, column 1
Class.Logger: line 47, column 1
Class.LWC_CaseHighlights.getCaseDetails: line 18, column 1
14:46:47.0 (11178717)|FATAL_ERROR|System.LimitException: Too many DML statements: 1

Class.Logger.setupOrgDefaults: line 2645, column 1
Class.Logger: line 47, column 1
Class.LWC_CaseHighlights.getCaseDetails: line 18, column 1
14:46:47.11 (11198328)|CUMULATIVE_LIMIT_USAGE
14:46:47.11 (11198328)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 0 out of 100
  Number of query rows: 0 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 1 out of 0 ******* CLOSE TO LIMIT
  Number of Publish Immediate DML: 0 out of 150
  Number of DML rows: 0 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10
```

This trace of this error is happening as part of a `@wire` function call:

```
    @AuraEnabled(Cacheable=true)
    public static DTO_CaseHighlightsResponse getCaseDetails( Id caseId, List<String> fieldPaths ) {
        final String METHOD_NAME = 'getCaseDetails()';
        Logger.debug( new LogMessage( LoggerConstants.METHOD_LOG_UNFORMATTED, CLASS_NAME, METHOD_NAME, LoggerConstants.IM_HERE ));

        try {
            // snip
        }
        finally {
            Logger.saveLog();
        }
    }
```

It appears that this is related to certain contexts not being able to do DML (e.g. create the initial LoggerSettings, if none exists)

https://www.levelupsalesforce.com/lwc-too-many-dml-statements-1

Creating the LoggerSettings__c entry (org defaults in our case) immediately stops this failure.

**Comment by jongpie** [comment]
Thanks for reporting this! I'll plan to fix this in my open PR #191 (which will be release v4.6.8). Let me know if you run into any other issues!

**Comment by jongpie** [comment]
@arbokrad I was able to fix this as part of PR #191 by making 2 (fairly small) changes

- I've removed the DML entirely for `LoggerSettings__c` - this is at least the third time that it's caused issues for someone, so I think it's not the best approach to have DML automatically happen
- I've improved how the in-memory version of `LoggerSettings__c` is initialized in `Logger.getUserSettings()` so that it correctly loads all of the fields' default values

With these 2 changes, if an org does not have `LoggerSettings__c` configured, then Logger will still function - it will just use the default field values for each of the fields on `LoggerSettings__c`.

**Comment by jongpie** [comment]
@arbokrad I've just release a new version of the unlocked package, [v4.6.8](https://github.com/jongpie/NebulaLogger/releases/tag/v4.6.8), which includes a fix for this. Thanks again for reporting this issue!

**Comment by sjurgis** [comment]
@jongpie what sort of magic does nebula do to publish events in this context? I'm working on some naive logging implementation and noticed developers before me disabled logging when context is cacheable.

I've just tried to publish some events and while they seem to publish, the subscriber never gets called. Wonder if you ever seen this.
