### ISSUE TITLE
LogBatchPurger should also delete any Log__c records with 0 related LogEntry__c records

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#223]
As discussed with @starkguerraj in [issue 166](https://github.com/jongpie/NebulaLogger/issues/166#issuecomment-939034648), it sounds like there is still some issue with `Log__c` records not being deleted, even if they do not have any related `LogEntry__c` records. The query in `LogBatchPurger` should be updated to delete `Log__c` records where `TotalLogEntries__c` == 0, regardless of the value in `RetentionDate__c`.

**Comment by starkguerraj** [comment]
That's great, thank you.
