### ISSUE TITLE
Flow Log Entry - if Record Id is blank, action should not fail

### ISSUE THREAD

**Issue by solo-1234** [jongpie/NebulaLogger#230]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.6.9	

### New Bug Summary

Hi! I am using the flow action to create log entries. If the optional Record ID parameter is included, but the var passed is null, the flow throws an error:

An Apex error occurred: System.StringException: Invalid id: 
  ![image](https://user-images.githubusercontent.com/59446952/137364581-e89ecb32-15b4-412f-93f7-d746a8501b70.png)

I'd prefer if it just proceeded to create the log without a related record.

Thanks for your help!

**Comment by jongpie** [comment]
@solo-1234 I was thinking of closing this issue, but wanted to check with you first - is this still an issue? I think a while ago, I made the Record Id parameter optional, so it should handle `null` in the current versions, but let me know if you've seen any issues with this lately.

**Comment by solo-1234** [comment]
Hi, thanks for following up! I have no recollection of this :D I haven't gotten that error in ages so I would assume it's fixed. Thanks!

**Comment by jongpie** [comment]
Hahaha, perfect! I'll close this out then, thanks!
