### ISSUE TITLE
Installation Failed: You reached the limit for dashboards run as the logged-in user.

### ISSUE THREAD

**Issue by MorganMarchese** [jongpie/NebulaLogger#247]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.6.11

### New Bug Summary

Nebula Logger installation fails with the following error when the Organization already has reached its limit of Dynamic Dashboards.

---------------------------------------

Your request to install package "Nebula Logger Admin enhancements - new dashboard, reports, and error email alerts" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.

Package: Nebula Logger (04t5Y0000015l2q) Error Number: 1801218379-1979237 (641199103)
Problem:

1. (LogDashboards/LoggerAdmin) You reached the limit for dashboards run as the logged-in user.
LogDashboards/LoggerAdmin: You reached the limit for dashboards run as the logged-in user.

2. (LoggerConsoleHomePage) Component [desktopDashboards:embeddedDashboard] attribute [dashboardName]: Invalid dashboard Unique Name LoggerAdmin - no dashboards found.
LoggerConsoleHomePage: Component [desktopDashboards:embeddedDashboard] attribute [dashboardName]: Invalid dashboard Unique Name LoggerAdmin - no dashboards found.

**Comment by benji1304** [comment]
Also got this error when installing into my production org

**Comment by jongpie** [comment]
@MorganMarchese and @benji1304 thanks for reporting this! This was my mistake - I did not take into account the org limit for dynamic dashboards. I'll resolve this issue in PR #237 (which will be released as v4.6.12) by removing the new dashboard altogether, and instead make it an optional add-on (available as a separate unlocked package).

**Comment by jongpie** [comment]
@MorganMarchese, @benji1304 and @kbomma-sf - I've just released [v4.6.12](https://github.com/jongpie/NebulaLogger/releases/tag/v4.6.12), which removes the problematic dashboard from the core package. Hopefully this resolves your upgrade errors - let me know if you run into any other issues!
