### ISSUE TITLE
Toggle to not save logs to the object and write to Apex Debug logs

### ISSUE THREAD

**Issue by anandbn** [jongpie/NebulaLogger#258]
### New Feature Summary

Add a `LoggerSettings` to turn on / off the saving of logs to logging custom objects. When turned off, it should write the log to Apex debug log instead so that we can use the standard debug log view to view the logged info.

**Comment by jongpie** [comment]
Hi @anandbn - thanks for the suggestion! I think this is a great idea - we're also looking into adding support for logging to a BigObject (see #117), so I think we'll try to bundle this enhancement together so that there's more control overall of where data is logged. 

I'm not sure exactly when we'll get this implemented, but I'll keep you updated on the progress!

**Comment by jongpie** [comment]
Hey @anandbn - I was able to implement this as part of the next release, `v4.7.0` (PR #274). I'm planning to release this in about 2 weeks, once all orgs have been upgraded to Spring '22 release (which should happen on February 12). The PR includes 2 new fields that provide control over creation of platform event and custom object records:

1. `IsSavingEnabled__c` - when disabled, any calls to `Logger.saveLog()` are ignored. This allows you to still use Logger for output Apex debug statements, but completely disable saving/publishing of the platform event `LogEntryEvent__e`.
2. `IsPlatformEventStorageEnabled__c` - this fields controls if `LogEntryEvent__e` platform events are transformed & stored in the custom objects `Log__c` and `LogEntry__c` (when `IsSavingEnabled__c` == true).

![image](https://user-images.githubusercontent.com/1267157/150840853-47fb72c6-f15b-418e-a539-35b2172dcd76.png)

**Comment by jongpie** [comment]
@anandbn this feature has _finally_ been released! It's available in [v4.7.0](https://github.com/jongpie/NebulaLogger/releases/tag/v4.7.0).
