### ISSUE TITLE
Leverage Winter '21 new RequestId and Quiddity

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#27]
Upgrade to Winter '21 (API v50.0) and either add these fields in addition to, or instead of, `Log__c.TransactionId__c`. If they can be used as replacement, then the class `Uuid` could probably be removed from the repo as well.

https://releasenotes.docs.salesforce.com/en-us/winter21/release-notes/rn_apex_Runtime_Detection.htm

**Comment by jamessimone** [comment]
Thanks! Excited to be working on this.
