### ISSUE TITLE
Unit tests are failing, when running user's language is not English

### ISSUE THREAD

**Issue by derroman** [jongpie/NebulaLogger#271]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.6.14

### New Bug Summary

We are using NebulaLogger in several projects successfully. Unfortunately several unit tests are failing - all we the same root cause:

`System.QueryException: List has no rows for assignment to SObject`

The reason can be found here:

https://github.com/jongpie/NebulaLogger/blob/f190ab12b19baa14d78921d929b3c8a57f20a93b/nebula-logger/core/tests/common/classes/LoggerTestUtils.cls#L10

This query - using a profile name as where clause - will fail, if the running user's language is not English. In our Orgs the user uses usually German as language, so the profile name will be "Standardbenutzer" instead of "Standard User". So this query fails. 

Workaround:
* Switch running user's language to English

**Comment by jongpie** [comment]
Hi @derroman - thanks for reporting this! I am nearly done with a fix for this - I'll include the fix for this issue in the next release, `v4.6.17`. I'm not 100% sure when I'll have the release ready, but probably it will be done within the next few weeks.

**Comment by jongpie** [comment]
@derroman this should the new release [v4.7.0](https://github.com/jongpie/NebulaLogger/releases/tag/v4.7.0) - I've changed the approach in some of the tests to no longer depend on a specific profile, which should avoid the issue with trying to query for profiles. Thanks again for reporting this issue!
