### ISSUE TITLE
Add method Logget.getScenario() and new DefaultLogScenario__c field on LoggerSettings__c

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#279]
### Discussed in https://github.com/jongpie/NebulaLogger/discussions/278

<div type='discussions-op-text'>

<sup>Originally posted by **dschibster** February  6, 2022</sup>
Hi there @jongpie!

I am in the middle of cleanup project, and want to get to use Nebula Logger to finally get some transparency about when automation go awry. One thing I want to use extensively is the scenario feature. However, I think that when you enter Apex from a Component, it's pretty easy to set one, but not so much when you run a basic update from UI. The thing is, I was thinking if setting a Default Scenario in these cases would be wise, which I wouldn't be able to do right now because I wouldn't be able to inspect the Scenario at runtime without fiddling in the code.

What do you think about the option of adding a Default Scenario, and what would you say about adding a getter to check if we need to set one in our Triggers?</div>

**Comment by jongpie** [comment]
@dschibster, another update for you on this - I've added [some changes](https://github.com/jongpie/NebulaLogger/commit/4f41ad5ef3b3bbe7e09af04b588436cab55505a7) for this enhancement, so this will definitely be included in the next release, `v4.7.0`. The changes include 2 items:

- New method `Logger.getScenario()`, which returns the value for the current transaction.
- New field `LoggerSettings__c.DefaultLogScenario__c` (text 255) - this can be used for configuring a default scenario.
  - If this field is set, and nothing in Apex/Flow/Lightning Components calls `Logger.setScenario(String)`, then the default value will be used.
  - If this field is set, and the scenario is set in Apex/Flow/Lightning Components, then the value provided in Apex/Flow/Lightning Components will be used.
  - The new settings field will be configurable on the `loggerSettings` lwc that's avaiable within the Logger Console app:
    ![image](https://user-images.githubusercontent.com/1267157/153535299-60f10f70-77eb-4623-80a8-ce3e679032aa.png)

I think this covers all of the functionality you mentioned in #278, but let me know if you have any feedback!

**Comment by dschibster** [comment]
Thanks a lot for the quick implementation, this looks like exactly what I needed.

**Comment by jongpie** [comment]
@anandbn this feature is now available in [v4.7.0](https://github.com/jongpie/NebulaLogger/releases/tag/v4.7.0). Let me know if you have any other suggestions - thanks again for your feedback!
