### ISSUE TITLE
Get the unlocked package listed on AppExchange

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#290]
For a few years, I've been avoiding going through the process of putting Nebula Logger on AppExchange - but given how the project continues to grow in both popularity and functionality, I think it finally makes sense to (try to) get it published on AppExchange. For now, I'm only planning to publish the unlocked package - depending on how the process goes, I may eventually do the same with the managed package as well, but it'll be just the core unlocked package to start.

**Comment by jongpie** [comment]
After looking into this a bit more + chatting with others that are more familiar with publishing on AppExcha he, I've decided to not release either package on AppExchange. It sounds like it would add some significant delays & bureaucracy to the current release process, and I don't see any advantage to doing so at this time.

**Comment by nvuillam** [comment]
@jongpie an AppExchange package that passed the security review does not count in the org limits (max apex lines, max custom objects, etc.... ) so for big orgs it would be a game changer ^^

**Comment by jongpie** [comment]
@nvuillam I have definitely thought about this more (and continue to think about this), but for now, I'm still not going to get it listed on AppExchange for 2 reasons:
1. **Separate app limits would break parts of Nebula Logger**. Security reviewed apps get their own set of [transaction limits](https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_apexgov.htm?ref=cloudfiles) for things like SOQL queries, etc. This would actually break some functionality in Nebula Logger - it automatically tracks these transaction limits, so having it run with its own set of limits would no longer tell admins/developers about the limits consume by their own code.
2. **The review process would (probably) slow me down**. Admittedly, I have never actually gone through the AppExchange security review process - but I spend a _significant_ amount of time already working on Nebula Logger, and I am very worried that going through AppExchange would slow me down/prevent me from focusing on delivering new enhancements & bugfixes.

I really appreciate the input (as well as all of your own contributions to the Salesforce ecosystem & open source 🥳  ), and I'll definitely continue to consider getting it listed on AppExchange. But at least for now, I'm going to wait on having it listed on AppExchange.

**Comment by nvuillam** [comment]
@jongpie I totally understand your reasons, OpenSource is time consuming and maintenance can quickly become a part-time-unpaid-occupation :D

If someday you decide to go for a security review, I'll be delighted to assist you :) ( I only did it for my clients but I'm pretty sure it's the same for free apps, and at worse I'll call @VinceFINET for help 😄 

Thanks again for Nebula, we started to use it on a project and we like it :)

**Comment by jongpie** [comment]
Hahaha, that sounds great, and I will definitely reach out to you for help if/when I decide to consider it. Right now, I'm focusing on implementing some bigger enhancements over the next few months, but perhaps next year, I can revisit listing it on AppExchange.

That's very cool to hear that you're using it on a project - let me know if you have any feedback or questions!
