### ISSUE TITLE
Enhancements for logEntryEventStream LWC

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#293]
There are a couple of new features I'd like to eventually include in the LWC `logEntryEventStream`

- Collapsible sidebar (same way that the sidebar collapses in object tabs within a console app)
- Ability to view console in full-screen
- Ability to toggle between the existing console view and a new tabular view (using `lightning-datatable`)
  - At lead within a tabular view, it might be nice to be able to customize which columns are displayed. The configuration could possible be stored in `LoggerParameter__mdt` (so it would be customizable, but only at the org level - users wouldn't be able to have their own customized views, which might be ok?)

**Comment by mar-ben** [comment]
@jongpie shall i work on this?

**Comment by mar-ben** [comment]
@jongpie  Please find the below updated logEntryStream component UI. Let me know if any suggestions. 

Sidebar expanded (table view):
![image](https://user-images.githubusercontent.com/15126069/174215609-6fa8df66-9b74-4092-817d-f8d09337b097.png)

Sidebar collapsed (console view):
![image](https://user-images.githubusercontent.com/15126069/174217149-1e8834a5-62b8-4f66-a4d5-0eebb8bddfb6.png)

Full screen mode: 
![image](https://user-images.githubusercontent.com/15126069/174216780-13e1d216-8222-4ec8-af6f-7ec0a75609c0.png)

**Comment by jongpie** [comment]
@mar-ben this looks amazing!! This is exacrly what I was hoping for - I don't have any suggestions right now, so feel free to submit a PR and I can do a code review.

**Comment by mar-ben** [comment]
@jongpie I am fetching the the Datatable columns configured in LoggerParameter__mdt using apex method `LoggerParameter.getStringList `. But this method is not annotated as "AuraEnabled". Can I annotate this method as "AuraEnabled" and call it directly from LWC ? or call it from LWC component's controller?

**Comment by jongpie** [comment]
@mar-ben that's a good question! I think for now, I want to avoid annotating the methods in `LoggerParameter` as AuraEnabled -  I might make some other changes to the `LoggerParameter` class in a month or two, so I'm hesitant to use `@AuraEnabled` right now. Could you instead create a new Apex controller class for the LWC? It doesn't currently have an Apex controller, but I think this is a good time to create one. The Apex class could be called something like `LogEntryEventStreamController`.
