### ISSUE TITLE
Add helper methods for Database.XResult and Database.XResult lists to log on errors

### ISSUE THREAD

**Issue by jamessimone** [jongpie/NebulaLogger#295]
### New Feature Summary

Currently, classes with multiple DML operations happening at once where `allAtOnce` is set to false have to manually iterate through their Database.SaveResult, Database.UpsertResult, Database.DeleteResult, Database.UndeleteResult, etc ... when deciding what to log.

I'd like to propose that Logger expose a helper method for _only logging errors_ such that:

```java
List<Object> dmlOperationsToVerify = new List<Object>();
dmlOperationsToVerify.addAll(Database.insert(someListToInsert, false));
dmlOperationsToVerify.addAll(Database.delete(someListToDelete, false));
Logger.logDMLErrors(dmlOperationsToVerify, LoggingLevel.WARN);
```

Not tied to the method name `logDMLErrors` by any means, but it would be nice for Logger to be able to do the list iteration - regardless of the underlying Database result type - and only log where `.isSuccess()` is false. It's ... highly unfortunate ... that there's no base class for all of the different database result classes, but Logger having a method like this would help to ease the pain associated with working with these DML operation lists.

**Comment by jongpie** [comment]
@jamessimone I love this idea! My struggle right now is deciding if it makes sense for this to be a method in `Logger` or in `LogEntryEventBuilder`, but I think experimenting with both options should be fairly quick.

Regardless of where the method is implemented, what would you expect to happen if all of the Database results have `.isSuccess() == true`? Should it skip adding an entry altogether? Or should it still add a log entry, with some kind of indication that there weren't any failures? Based on our last conversation about this + your original description above, I'm thinking it'd be the first option (only add log entries if/when there are failures), but just wanted to check with you on that detail. Let me know what you think!

**Comment by jamessimone** [comment]
I think you’re right, that no errors should lead to no log entries!

**Comment by jongpie** [comment]
Ok, cool, that makes sense, and I'm on board with adding the method to `Logger` instead of `LogEntryEventBuilder`. I think I'd want to go with a slightly different method name & signature to keep things consistent with the existing methods + parameters, maybe something like this (with several overloads for the different result classes)...

```java
public static void logDatabaseErrors(LoggingLevel loggingLevel, String message, List<DatabaseResult classes> results) { }

public static void logDatabaseErrors(LoggingLevel loggingLevel, LogMessage logMessage, List<DatabaseResult classes> results) { }
```

I guess the methods could return `List<LogEntryEventBuilder>` to keep it similar to how the "normal" logging methods (`Logger.error()`, `Logger.warn()`, etc) all return a single instance of `LogEntryEventBuilder`, but `void` might be good enough to start
