### ISSUE TITLE
Add the ability to manually run LogBatchPurger via a button click

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#304]
A new button labeled "Batch Purge" should be added to the `Log__c` tab/list views. When clicked, it should display a new LWC with details about logging data that will soon be deleted by `LogBatchPurger`, as well as a button to run `LogBatchPurger` ad hoc.

- The LWC should display metrics for number of `Log__c`, `LogEntry__c`, and `LogEntryTag__c` records to purge, for TODAY / THIS WEEK / THIS MONTH. Each timeframe should have the data group by the value of `Log__c.LogPurgeAction__c`
- The LWC should have a section to view any scheduled jobs for `LogBatchPurgeScheduler` (query below), with possible options to delete each scheduled job and/or to create scheduled job. Results could be displayed in a datatable (yuck), with a column to indicated scheduled vs running instance (with polling to refresh status changes), number of batches total, number of batches completed, number of batches with errors, created by id, timestamps, etc.
```java
List<AsyncApexJob> scheduledJobs = [
    SELECT ApexClassId, Id, JobItemsProcessed, JobType, Status, NumberOfErrors, MethodName 
    FROM AsyncApexJob  
    WHERE JobType IN ('BatchApexWorker','ScheduledApex')
    AND ApexClass.Name = :LogBatchPurger.class.getName()
];
```
- The LWC should display a button to run `Database.executeBatch(new LogBatchPurger, 2000);`. Only users with a new custom permission ('CanExecuteLogBatchPurger' or something similar?) should be able to view or click the button

**Comment by jamessimone** [comment]
Ooooh

**Comment by jongpie** [comment]
@jamessimone our recent adventures with data migrations + limited prod access made me think this might be a useful addition 😄

**Comment by jamessimone** [comment]
Yeah I love this idea. It's a great way to give people more control/insight over how and when the purger runs.

**Comment by jongpie** [comment]
@mar-ben that would be incredible, thanks for offering to contribute! When I originally wrote this issue, I was thinking that tabular format might be the simplest/easiest approach, but to be honest, I haven't spent much time thinking about what exactly the UI should look like - if you have other ideas in mind, I'm very open to any suggestions. (Alternatively, if you'd instead like more detailed requirements, I'm also happy to spend some time designing the UI/creating a mockup, just let me know works best for you.)

**Comment by mar-ben** [comment]
@jongpie Please find the below screenshot of the LWC component UI. Can you review and let me know what you think? 

<img width="1527" alt="image" src="https://user-images.githubusercontent.com/15126069/169677863-96551843-bc9e-4b0d-92f1-f504e5c85eea.png">

**Comment by jongpie** [comment]
@mar-ben that looks incredible! Offhand, I don't have any changes to suggest as far as the look & feel, it seems to have everything that I was hoping to have. Feel free to create a pull request whenever you are ready, and I can review the code changes.

**Comment by jongpie** [comment]
@mar-ben another update on this - I'm working on creating release `v4.7.8`, which will include your changes for this enhancement. When the pipeline ran for PR #329, it showed some additional issues for the managed package, so I've made a few small changes to your work so that everything works in the managed package:

- The aggregate queries for `Log__c`, `LogEntry__c`, and `LogEntryTag__c` failed within the managed package because the managed package has a namespace on the fields. I've fixed it by adding a field alias to the aggregate queries.
- The "Batch Purge" button on the `Log__c` tab didn't work in a managed package because the tab name (within the weblink formula) needs to include the manage package's namespace, which is apparently difficult to do. Instead of displaying the new LWC via a weblink on `Log__c`, I've changed it so that the tab for the LWC `logBatchPurge` is included as a tab in the app "Logger Console" (see screenshot below). I think this is probably better anyway, as it could have been confusing to have both "mass delete" and "batch purge" as buttons on `Log__c` list views
  
  ![image](https://user-images.githubusercontent.com/1267157/173399726-9a34a8da-8bea-4df8-bdbc-4cde6245e15f.png)

I'm wrapping up some additional testing today, and hope to have this finally released this week.

**Comment by jongpie** [comment]
@mar-ben I've finally released this in [v4.7.8](https://github.com/jongpie/NebulaLogger/releases/tag/v4.7.8)!! Thanks again for all of your help!

**Comment by mar-ben** [comment]
Yay!.. my first pull request is merged.. @jongpie Thank you so much for making this happen !!!.

**Comment by jongpie** [comment]
@mar-ben it's been a pleasure collaborating with you on this, I'm very excited to start using the new component 🥇
