### ISSUE TITLE
Logger.setScenario() has typo causing exception

### ISSUE THREAD

**Issue by feisley** [jongpie/NebulaLogger#326]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.7.6

### New Bug Summary

When calling Logger.setScenario() the following exception is thrown:

System.FinalException: Record is read-only
Class.Logger.setScenario: line 2703, column 1

This appears to be caused by a typo on line 2703 of Logger:

https://github.com/jongpie/NebulaLogger/blob/main/nebula-logger/core/main/logger-engine/classes/Logger.cls#L2703

`if (scenarioRule.IsEnabled__c = true && scenarioRule.Scenario__c == scenario) {`
should be
`if (scenarioRule.IsEnabled__c == true && scenarioRule.Scenario__c == scenario) {`

**Comment by jongpie** [comment]
Thanks for catching this, and apologies for any issues it's causing! I'll try to get a bugfix release published today to correct this.

**Comment by jongpie** [comment]
@feisley this should be fixed now, I've just released [v4.7.7](https://github.com/jongpie/NebulaLogger/releases/tag/v4.7.7) with a fix for this. Let me know if you come across any other issues!
