### ISSUE TITLE
Dead Link in Readme

### ISSUE THREAD

**Issue by justin-lyon** [jongpie/NebulaLogger#331]
### Package Edition of Nebula Logger

Managed Package

### Package Version of Nebula Logger

n/a

### New Bug Summary

At the bottom of [LogMessage](https://github.com/jongpie/NebulaLogger#using-logmessage-for-dynamically-generated-strings) the documentation link is broken.

<img width="964" alt="image" src="https://user-images.githubusercontent.com/9729366/173564659-02536fff-bcda-4f08-b153-8e2790645cbf.png">

**Comment by jongpie** [comment]
Thanks for catching this! I'll have to fix this link + update a lot of content in README (I'm planning to move some content to the wiki). I've been neglecting some of the documentation lately, I'll spend some time getting everything updated & fixed.

**Comment by justin-lyon** [comment]
I think moving stuff out of the readme and into a wiki would be awesome.
