### ISSUE TITLE
Custom Object LoggerSObjectHandlerParameter__mdt from managed package not present for recipes

### ISSUE THREAD

**Issue by hernandezjesus** [jongpie/NebulaLogger#339]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

main branch

### New Bug Summary

1. Pull the latest version of the repository
2. Create a new scratch org from .\config\scratch-orgs\base-scratch-def.json
3. Push metadata using `sfdx force:source:push`

Expected Behavior: All metadata and folders get deployed in the order defined in sfdx-project.json

Actual Behavior: Found myself with the following error:

nebula-logger\recipes\profiles\Admin.profile-meta.xml  In field: field - no CustomObject named LoggerSObjectHandlerParameter__mdt found
ERROR running force:source:push:  Push failed.

The Admin profile has reference to a Custom Object that is only present in nebula-logger\managed-package. This is not included in the sfdx-project.json.

**Comment by jongpie** [comment]
Thanks @hernandezjesus for reporting this! I'll get this fixed in the Admin profile ASAP - I'll eventually switch to providing a permission set for the recipes instead of using the Admin profile.
