### ISSUE TITLE
Is it possible to configure Logger to not log for specific Apex classes/triggers?

### ISSUE THREAD

**Issue by mikesobczak** [jongpie/NebulaLogger#347]
Or would I need to write custom code to disable the Logger wherever needed?

**Comment by jongpie** [comment]
@mikesobczak great question! At the moment, this isn't currently supported - I had started a prototype of this feature about 1.5 years ago, but never finished implementing it. I can revisit this idea sometime in the next few months. - in the meantime, you'll have to write your own code to handle this.

**Comment by jongpie** [comment]
Closing this out, this is now possible using the changes released in [`v4.8.2`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.8.2)
