### ISSUE TITLE
NullPointer Exception when addTag method is called upon the return Object of Logger.logDatabaseErrors()

### ISSUE THREAD

**Issue by NX-Mirco-Centrone** [jongpie/NebulaLogger#360]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v.4.8.0

### New Bug Summary

addTag() method throws a NullPointer Exception when is called from the LogEntryEventBuilder return Object of logDatabaseErrors().

**Comment by jongpie** [comment]
Thanks @NX-Mirco-Centrone for the info! I'm not sure why I originally designed the `logDatabaseErrors()` method to sometimes return null - it's very inconsistent with how the other methods work. I'll change this ASAP.

**Comment by jongpie** [comment]
@NX-Mirco-Centrone I was able to get this fixed ([see changes](https://github.com/jongpie/NebulaLogger/commit/82f00974c44e45c003e23223010e0d1f7ee2d23c)), it'll be included in the next release, `v4.8.2`

**Comment by NX-Mirco-Centrone** [comment]
@jongpie Thank You for your amazing work!

**Comment by jongpie** [comment]
Closing this out, this has been released in [`v4.8.2`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.8.2)
