### ISSUE TITLE
Log scenario migration script bug

### ISSUE THREAD

**Issue by fehays** [jongpie/NebulaLogger#363]
There's a bug on line 16 of the transaction scenario migration script.

`System.SObjectException: SObject row was retrieved via SOQL without querying the requested field: Log__c.TransactionScenario__r`

Need to add this field to the select.

[https://github.com/jongpie/NebulaLogger/blob/5f59b7a9d04e1e7f0d649e9712f82a74961db86d/scripts/data/migrate-log-scenario-field-to-logger-scenario-object.apex#L16](url)

**Comment by jongpie** [comment]
Thanks for reporting this @fehays! I'll get this fixed in the next release (v4.8.2)

**Comment by jongpie** [comment]
Closing this out, this has been fixed in [`v4.8.2`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.8.2)
