### ISSUE TITLE
Add logging for FlowExecutionErrorEvent in Async Failures Addition plugin

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#372]
Salesforce has a platform event object called [`FlowExecutionErrorEvent`](https://developer.salesforce.com/docs/atlas.en-us.platform_events.meta/platform_events/sforce_api_objects_flowexecutionerrorevent.htm) that generates events for errors in screen flows (autolaunched flows are not supported unfortunately). It seems conceptually similar to Apex's `BatchApexErrorEvent`, so this would be a nice fit for the [Async Failures Additions plugin](https://github.com/jongpie/NebulaLogger/tree/main/nebula-logger/plugins/async-failure-additions).

I'm not sure exactly where some of the fields on `FlowExecutionErrorEvent` would map to in Nebula Logger, but hopefully some of the existing Flow-specific fields on `LogEntryEvent__e` and `LogEntry__c` can be reused.

**Comment by jamessimone** [comment]
@jongpie thanks! I'll aim to tackle this next week

**Comment by jamessimone** [comment]
Oops the week went by and I knew I had forgotten something. I may be able to take a stab at this this weekend!

**Comment by jongpie** [comment]
No rush at all!
