### ISSUE TITLE
Data skew issues with Tag and Scenario features

### ISSUE THREAD

**Issue by rmccu** [jongpie/NebulaLogger#388]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.6.16

### New Bug Summary

Tags will typically represent a small number compared to the number of Log Entries that they are associated with (via Log Entry Tag). This will result in a data skew issue where maybe a few dozen Tags exist, but are associated with millions of Log Entries.

Issues manifest itself in record locking when a Log Entry Tag is inserted, it will lock the Tag record (because it is a master-detail and any insert/update of a child record locks the parent). This will also cause issues when attempting to clean up logs. Deleting a Log, cascades into the Log Entry and Log Entry Tag. Even if you delete the Log Entry Tag first and do not rely on the cascading delete (which is what the Log Purge class does), it will still cause the tag records to get locked and cause locking issues with existing logs being generated and then the Log Entry Tag records being deleted.

I know that my version of Nebula does not include the _Scenario_ functionality, but this issue will apply to it as well.

I don't think we have a lot of options for addressing this. We could look at changing the relationship from Log Entry Tag to Tag from being a master-detail to just a standard Lookup and remove any master-detail dependent functionality (like the roll-up summary on Tag). This would at least prevent the Tag record from locking when child Log Entry Tag records are inserted, updated, or deleted.

Another option could be to have a flag in the settings that would use a fallback tagging solution, like putting the tags into a text field or multi-select pick-list on the Log Entry record? I know this isn't ideal, but for our volume, it would be preferable as we are experiencing severe performance/locking issues due to the data architecture of Tagging.

**Comment by jongpie** [comment]
@rmccu I'm still evaluating a few options for this, but think I'm going to end up adding some new flags (stored in `LoggerParameter__mdt`) to control how tags & scenarios are stored

- For tags, it will still store data in `LoggerTag__c` and `LogEntryTag__c` by default (current functionality) - but I'll also use a new flag to provide the ability to instead store the tags in a new long textarea field, `LogEntry__c.Tags__c`. The platform events already use this approach via the field `LogEntryEvent__e.Tags__c`, so I'm not expecting any new issues as far as truncating/missing some tags
- For scenario, it will conceptually be the same - by default, the existing functionality will be to store the data in the `LoggerScenario__c` object, and a new flag will control if scenario information is instead stored in text fields on `Log__c` and `LogEntry__c`

I'll circle back to this in a few weeks, I'll let you know for sure how I end up implementing this. Thanks again for all of your feeback!

**Comment by rmccu** [comment]
Sounds good! Appreciate you looking into this.


*Ryan McCullough*
***@***.***

**Comment by rmccu** [comment]
I meant to also add, we are working towards connecting the Nebula PA to
AT&T's ELK system. Once we do this, it should greatly improve the current
scale challenges.

However, I was thinking about this a bit more. It would be great if you
could have some different configurations based on the consumer. For
instance, log4j used to let you configure the log settings per output
channel (e.g. the console output could be different than the file output).
I think this could be useful if we wanted to set the logging for their ELK
system, but be able to turn logging up or down for specific users, types,
etc., but only for the logs written into Salesforce.

Is this even possible? Since we fire the PE and it is subscribed to by
whoever, and this would need to be controlled by the subscriber. I don't
know, but this would be useful for our use-case. Anyways, I will noodle it
as well, but thought I would mention it if you had some ideas. I know you
were talking about the rule/criteria stuff in Nebula as a way to help with
this, but I don't think that gets me all the way there for this particular
use-case (different log detail for the subscribers).


*Ryan McCullough*
***@***.***

**Comment by jongpie** [comment]
@rmccu there is _limited_ way of doing what you're describing. Right now in `v4.8.3`, you can control if data is stored in the custom objects. The field [`LoggerSettings__c.DefaultPlatformEventStorageLocation__c`](https://github.com/jongpie/NebulaLogger/blob/v4.8.3/nebula-logger/core/main/configuration/objects/LoggerSettings__c/fields/DefaultPlatformEventStorageLocation__c.field-meta.xml) controls where the platform events are stored (which means it's also dependent on platform events being published for this to work). By default, it's set to `CUSTOM_OBJECTS`, but if you set it to `null`, then platform events will still be published via the `EventBus` by the `User`/`Profile`, but the platform events won't be written to the custom objects.

I'm not sure that this fully meets your use case, but let me know what you think of this option. I think it's is useful if you just want to fully disable storing data in the custom objects for certain users/profiles, but I could see situations where you want to save a subset of the platform events into custom objects (which isn't currently possible).

**Comment by jongpie** [comment]
@rmccu I've just released these changes in [v4.9.9](https://github.com/jongpie/NebulaLogger/releases/tag/v4.9.9)!! 🥳

**Comment by rmccu** [comment]
Thanks!
