### ISSUE TITLE
Provide a solution for indexing the field LogEntry__c.OriginLocation__c 

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#400]
thanks for looking at this, but unfortunately, I can't support this change - the `externalId` attribute for fields cannot be changed in managed packages ([source](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/packaging_packageable_components.htm#mdc_custom_field) & shown in screenshot below). This is a frustrating limitation, but since I'm supporting both a managed package & unlocked package for Nebula Logger, I want to keep the metadata as consistent as possible.

![image](https://user-images.githubusercontent.com/1267157/197042464-e4bad393-cd7b-4e66-bdd1-6be0311ef490.png)

I'm unfortunately going to have to close this pull request for now, but I'll log an issue to see if there are any ways to support indexing the data in the future. One possible solution is to deprecate the `OriginLocation__c` field and replace it with a new text field that's flagged as an external ID - this could cause a headache in a lot of orgs that already use Nebula Logger (they would have to update list views, reports, etc. to use the new field), but I'm still going to consider it as a possible solution.

For your specific use case, can you share any details on issues you're running into? I'm guessing that reports & list views in your org might be slow when filtering on `OriginLocation__c`, but could you share some specifics on the kinds of issues you're facing? Are things slow to load? Or do they timeout entirely?

_Originally posted by @jongpie in https://github.com/jongpie/NebulaLogger/issues/395#issuecomment-1286049573_

**Comment by jongpie** [comment]
@JeroenSfdc, I think there's a solution available for this! After [a fun dicussion on the sfxd discord server](https://discord.com/channels/246568944213819393/731220916846985217/1044610855624527952), it looks like the poorly-documented-but-new metadata type `CustomIndex` is now available - instead of needing to request Salesforce Support to create [custom indexes](https://developer.salesforce.com/docs/atlas.en-us.salesforce_large_data_volumes_bp.meta/salesforce_large_data_volumes_bp/ldv_deployments_infrastructure_indexes.htm), you can now create & deploy custom indexes like any other metadata type. And the new type is even [supported in packaging](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/packaging_packageable_components.htm#mdc_custom_index)! 🥳 

I'm going to try adding an index for `LogEntry__c.OriginLocation__c` and test out beta package versions of the unlocked & managed packages to see if there are any issues/concerns - if nothing comes up, I'll release a new package version that includes the custom index.

**Comment by jongpie** [comment]
@JeroenSfdc custom indexes are **_finally_** available in [the latest release of the managed package, `v4.12.0`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.12.0) 🥳

**Comment by JeroenSfdc** [comment]
> @JeroenSfdc custom indexes are **_finally_** available in [the latest release of the managed package, `v4.12.0`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.12.0) 🥳

Thanks for following-through on this one @jongpie 👍
