### ISSUE TITLE
Field-level Encryption for LogEntry__c fields

### ISSUE THREAD

**Issue by JeroenSfdc** [jongpie/NebulaLogger#405]
### New Feature Summary

`LogEntry__c` records could contain PII. Some of which can be taken care of using regex to filter information out.
My customer requires field-level encryption for any data potentially containing PII.
Ideally we would be able to mark a bunch of `LogEntry__c` fields as encrypted.

Specifically this set of fields:
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/27854769/202735760-8218554a-4fd2-4bfc-a754-841865866dea.png">

Do you know if other customers have done the same, would this pose potential risks for the package (other then overhead in encrypt/decrypt operations)?

**Comment by jongpie** [comment]
Hi @JeroenSfdc! Unfortunately, it's not feasible to use classic encryption for those fields - classic encryption [has several limits](https://developer.salesforce.com/docs/atlas.en-us.securityImplGuide.meta/securityImplGuide/fields_about_encrypted_fields.htm) that prevent being able to use it. Most notable, it limits text fields to 175 characters (and all of the fields in your screenshot are long text area fields)

![image](https://user-images.githubusercontent.com/1267157/203121181-ba80220f-c113-4798-83c5-5a5b423458d5.png)

I think if your customer is concerned about who can access the data (especially those specific fields in your screenshot), then the better approach is to focus on object-level security, field-level security, and record-level access. Logging data should be considered sensitive data anyway, and limiting overall access is a better, more scalable approach than trying to use classic encryption.

**Comment by jongpie** [comment]
I'm closing this issue since it doesn't seem technically feasible - if/when something changes, we can reopen it.

**Comment by JeroenSfdc** [comment]
I think we're fine. This is not about classic encryption, but shield platform encryption. Logged data can potentially hold PII and that would be a reason to encrypt the fields at-rest. As consumer of the package, I'd be able to do this - at least techncially. There is no change needed. But I'm bit worried about impact on future upgrades.

**Comment by JeroenSfdc** [comment]
What I noticed @jongpie is that when we set fields as encrypted, once we upgrade the managed package, the encryption is removed from the fields we encrypted on `LogEntry__c` (this is about Shield Platform encryption, not classic).
