### ISSUE TITLE
Add metadata examples for flow and apex

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#42]
Add a new folder (not used by sfdx-project.json) with example metadata to show how to add entries, save, pass an SObject, etc
- 1 flow
- 1 apex class or trigger 
- 1 aura component

This would give admins & developers some optional metadata to play around with in a sandbox to demonstrate how they can leverage Logger

**Comment by jongpie** [comment]
Closed in #119

**Comment by jamessimone** [comment]
Woohoo!
