### ISSUE TITLE
"Run all Tests" from IntelliJ Illuminated Cloud fails when Unit Test Class "Logger_Tests" is included

### ISSUE THREAD

**Issue by derroman** [jongpie/NebulaLogger#433]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.8

### New Bug Summary

Hi!

We use Nebula Logger in all our Salesforce related projects as unmanaged package. We've discovered, that running all unit tests from regular Salesforce Setup works just fine.

But when we use IntelliJ in combination with Illuminated Cloud 2 all tests fail with Error Code 500... I am absolutely unsure, if this is a problem of Illuminated Cloud or if this has to do with the specific test class mentioned in the title... So if this is not "your fault": never mind 😉

I just thought it's worth it to post it here, because this single unit test class is the only one, I've ever seen, where we can reproduce the behaviour.

![Configuration Settings](https://user-images.githubusercontent.com/3176905/209953472-1ac6d02f-57bb-4c2f-863d-8fc6f0bb558a.png)
(For the purpose of this screenshot, all unit tests have been selected manually)

When we now run all unit test, we get these error messages:
![Test Results](https://user-images.githubusercontent.com/3176905/209953689-6c2d2b03-f657-40db-95e2-198e0b8a6eda.png)

This is reproducible with the unit test class "Logger_Tests" selected. If we deselect it all tests run smoothly...

**Comment by jamessimone** [comment]
@SCWells72 tagging you here as this seems an issue with IC rather than with Nebula Logger.

**Comment by SCWells72** [comment]
If this is an IC2-specific behavior, please log a bug in the [IC2 public issue tracker](https://bitbucket.org/RoseSilverSoftware/illuminatedcloud/issues?status=new&status=open).

**Comment by derroman** [comment]
Created an issue here: https://bitbucket.org/RoseSilverSoftware/illuminatedcloud/issues/2296/running-all-unit-tests-in-ic2-fails-if-a

**Comment by jamessimone** [comment]
Thanks all - closing this one for now.

**Comment by derroman** [comment]
hi!

Just for your interest: there are some interesting new insights on the corresponding issue here: https://bitbucket.org/RoseSilverSoftware/illuminatedcloud/issues/2296/running-all-unit-tests-in-ic2-fails-if-a
