### ISSUE TITLE
Open Viewer button > Log File is missing many log entries

### ISSUE THREAD

**Issue by solo-1234** [jongpie/NebulaLogger#436]
On logs with many entries, clicking Open Viewer > Log File does not display all of them. For example, I have a log with 600+ entries which only shows 27 of them in the viewer.

**Comment by jongpie** [comment]
Thanks @solo-1234! I'm hoping that this is a fairly easy bugfix, I'll do some more analysis on it later this week.

**Comment by solo-1234** [comment]
Hi, just wondering if you got a chance to look at this. Thanks!

**Comment by jamessimone** [comment]
Nice work on this one! It was great to pair on the solution.

**Comment by jongpie** [comment]
Thanks again for the help, glad to know I wasn't missing an obvious explanation for this one 😅 I'm hoping to push the commit for this later today (just need to finish some unit tests)

**Comment by jongpie** [comment]
@solo-1234 it's finally fixed! I've just released the bugfix as part of the new version, [`v4.10.0`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.10.0) 🥳
