### ISSUE TITLE
Test fails since upgrading to newest version

### ISSUE THREAD

**Issue by solo-1234** [jongpie/NebulaLogger#437]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.9.9	

### New Bug Summary

Since upgrading to 4.9.9, I'm getting a test failure when running a deployment:
```
System.NullPointerException: Attempt to de-reference a null object
Class.FlowLogRepo_Tests.it_should_return_most_recent_log_in_flow_compatible_list: line 27, column 1
```
Any ideas? Thanks!

**Comment by jongpie** [comment]
@solo-1234 I think you have some old metadata in your org from before you started using the unlocked package - the classes `FlowLogRepo` and `FlowLogRepo_Tests` were [deleted when I released `v4.0.0`](https://github.com/jongpie/NebulaLogger/compare/v3.2.0-beta...v4.0.0) (the original release of the package).

If you're not using the `FlowLogRepo` class, then I'd suggest deleting it from your orgs. Let me know if you need help with how to delete the old classes!

**Comment by solo-1234** [comment]
Got it! I deleted those apex classes. Problem solved, thank you!

**Comment by jongpie** [comment]
Glad you were able to get it resolved! Let me know if you run into any other issues since upgrading.
