### ISSUE TITLE
Logger Settings: Unable to create new entry

### ISSUE THREAD

**Issue by chazwatkins** [jongpie/NebulaLogger#438]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.9.9

## Steps to reproduce

- Navigate to Logger Settings as `Logger: Admin`
- Click "New" button

## Expected Results

- Setup Location combobox is editable

## Actual Results

- Setup Location combobox is disabled

<img width="641" alt="Screenshot 2023-01-10 at 3 33 59 PM" src="https://user-images.githubusercontent.com/9411090/211667485-29a5b8d6-2d66-48a4-9062-284b9a16ea28.png">

## Environment Details

This occurs in three environments.
- Partial Sandbox on Spring '23 Preview
- Full Sandbox on Spring '23 Preview
- Production on Winter '23

**Comment by chazwatkins** [comment]
In `Logger.getUserSettings(User loggingUser)`, it appears that when you call it with `Logger.getUserSettings(new User())` in `LoggerSettingsController.createRecord` the org default is always returned instead of the intended new record with no Id.  The final `else` block below is never reached.  So, when the combo-box checks if the record id exists, it does exist and marks the combobox as read-only.

So, once you define an org default, you can't create new records anymore.

```apex
      LoggerSettings__c loggingUserSettings;
        if (loggingUser.Id != null && LoggerSettings__c.getValues(loggingUser.Id) != null) {
            // Check for User-level settings
            loggingUserSettings = LoggerSettings__c.getValues(loggingUser.Id);
        } else if (loggingUserSettings == null && loggingUser.ProfileId != null && LoggerSettings__c.getValues(loggingUser.ProfileId) != null) {
            // Next, check for Profile-level settings
            loggingUserSettings = LoggerSettings__c.getValues(loggingUser.ProfileId);
        } else if (LoggerSettings__c.getOrgDefaults().Id != null) {
            // Next, use the org defaults (if configured)
            loggingUserSettings = LoggerSettings__c.getOrgDefaults();
        } else {
            // Never called
            // Once an org default is created, the above clause always matches
            loggingUserSettings = (LoggerSettings__c) Schema.LoggerSettings__c.SObjectType.newSObject(null, true);
            if (
                LoggerParameter.QUERY_ORGANIZATION_DATA_SYNCHRONOUSLY == true &&
                LoggerEngineDataSelector.getInstance().getCachedOrganization()?.IsSandbox == true
            ) {
                loggingUserSettings.LoggingLevel__c = System.LoggingLevel.FINEST.name();
                loggingUserSettings.IsApexSystemDebugLoggingEnabled__c = true;
                loggingUserSettings.IsJavaScriptConsoleLoggingEnabled__c = true;
            }
        }
```

Once approach could be to add a check for `loggingUser.Id != null` on line 280.

```apex
...
        } else if (loggingUser.Id == null && LoggerSettings__c.getOrgDefaults().Id != null) {
...
```

Let me know your thoughts on a fix.  I'm happy to do a pull request with whatever you decide.

**Comment by jongpie** [comment]
Hi @chazwatkins thanks so much for reporting & figuring out this issue! I think I like your approach of adding a check for `loggingUser.Id != null` - that seems like it would handle the issue. You are more than welcome to submit a PR for this if you'd like, or I can handle creating it if you'd like, whatever you prefer!

**Comment by chazwatkins** [comment]
I'll submit a PR tonight or tomorrow with the fix and updated tests.

**Comment by chazwatkins** [comment]
I haven't forgotten about this one.  I'm working on the test scenarios.  @jongpie When are you planning to cut the v4.10.0 release?  I'll make sure to have it knocked out before.

**Comment by jongpie** [comment]
@chazwatkins no rush at all! It'll probably be sometime next week at the earliest before I'm ready to release `v4.10.0`, I have a few other projects that I'm working on in the meantime.
