### ISSUE TITLE
Consolidate all "This class intentionally does nothing" classes into a single directory so they can be ignored categorically in IDEs

### ISSUE THREAD

**Issue by SCWells72** [jongpie/NebulaLogger#439]
### New Feature Summary

Hi. I'm the developer of Illuminated Cloud 2 and opened your repo in that IDE to look into an issue reported by one of my users. In the process of setting up the IDE project I found a large number of Apex reference resolution issues that were caused by the stub types denoted as:

```
// This class intentionally does nothing - it's here to ensure that any references
// in Nebula Logger's codebase use `System.<Type>` instead of just `<Type>`
```

Would it be possible to move those into a dedicated directory separate from project's other Apex types that could be denoted as excluded in an IDE project to avoid resolution against those local types?

I'd also be curious to understand what the comment above actually means since references to those types _should_ already resolve to `System.<Type>` since `System` is an implicit namespace and does not need to be used for qualification.

**Comment by jongpie** [comment]
Hi @SCWells72 - [the classes you're referring to](https://github.com/jongpie/NebulaLogger/tree/v4.9.9/nebula-logger/extra-tests/classes) are in place because implicit namespacing isn't sufficient for this repo. The problem that has come up a lot over the last year is that Nebula Logger's unlocked package does not include a namespace, so it runs in the same default namespace as any other Apex classes deployed to an org - and in several orgs that are trying to install the unlocked package, the orgs have (for whatever reason) already created Apex classes that conflict with standard Apex classes in the `Schema` and `System` namespace (e.g., some orgs have classes named `LoggingLevel`, `Test`, `Type`, `UserInfo`, etc.).

To avoid package installation issues, I've added these extra classes to Nebula Logger's repo to ensure that the codebase always explicitly uses the `Schema` and `System` namespaces. I'm not very familiar with Illuminated Cloud or how it resolves Apex types, but conceptually, I would _want_ the IDE to resolve these classes, because I've intentionally included them to ensure that fully qualified class names are always used.

Let me know your thoughts on this!

**Comment by SCWells72** [comment]
And just to provide a bit more clarity on the behavior when these stub types are present, the IDE _does_ resolve to them, and that causes issues with chained expressions, e.g., `LoggingLevel.DEBUG` can no longer be resolved because `LoggingLevel` has resolved to the local stub type instead of `System.LoggingLevel` because of resolution order or precedence. Hopefully that makes sense...

**Comment by jongpie** [comment]
Hi @SCWells72 - apologies, I forgot to mention that the local empty stubs aren't included in the unlocked package, so they don't impact a subscriber's org. The classes are only used in 2 places:
1. My scratch orgs when I'm doing development - I deploy the stub classes & my own classes to a scratch org any time I'm working on an enhancement or bugfix
2. The pipeline also has the stub classes deployed, as another layer of validation

Effectively, the classes exist so that I can ensure that I'm following the correct approach of qualifying those type name references as `System.<TypeName>` or `Schema.<TypeName>` - with the stubs in the repo, if I add a line of code like `Test.isRunningTest()`, it will fail to deploy to my scratch org _because_ I've also deployed the empty `Test` stub to my scratch org. Without having the stubs, I don't have an easy way to validate that the codebase is using fully-qualified references like `System.Test` instead of `Test`.

Using the example of `LoggingLevel.DEBUG`, I don't want that to resolve for Nebula Logger's codebase, because I'm trying to avoid install issues in orgs that have a custom class named `LoggingLevel`. So, if the IDE can't resolve `LoggingLevel.DEBUG`, but can resolve `System.LoggingLevel.DEBUG`, then that's essentially the behavior I would want - I only want `System.LoggingLevel.DEBUG` to be resolved (when working on this repo).

**Comment by SCWells72** [comment]
I see. So I think that supports the original assertion here that it should be possible to exclude a single directory of these stubs from the project so that IDEs that perform reference resolution and build upon the resulting references for static code analysis, variant code completion, etc., are resolving against the system types and not these local stub types. The issue right now is that the stubs are in the same directory as (presumably) some other classes that should still available in to the project so it's not possible to exclude that exact subset of types. Does that make sense? Let me know if not.

**Comment by jongpie** [comment]
@SCWells72 could you give me a little guidance on how I can see the issues locally? I think it'd be helpful if I can could see the reference resolution issues in action - I've installed the community edition of IntelliJ and the Illuminated Cloud 2 plugin, but I'm not sure where to go from here.

**Comment by SCWells72** [comment]
@jongpie, what may be easiest would be for me to provide a branch with an IC2 project already set up properly. Then you'd just check out that branch in IC2, associate the project with a scratch org, push the metadata, and generate an OST. IC2 will guide you through all that upon opening the branch as a project. I can then tell you how to see the various things I'm seeing.

Let me know if that sounds good and I'll push a branch for you.

**Comment by jongpie** [comment]
@SCWells72 that sounds perfect! Just let me know once you have a branch ready, and I'll try to check it out ASAP.

**Comment by SCWells72** [comment]
@jongpie, will do. And I also noticed one thing while looking at this more that likely moves the ball back into my court on this. If that bears out as I think it will, we can probably just close this. However, there are a couple of other questions/comments I'd have based on this overall experience that you might find interesting. Let me get past that and I'll let you know how things look.

**Comment by jongpie** [comment]
Sure, just let me know how I can help - I'm using this as a great reason to play around with Illuminated Cloud anyway (which I've been meaning to do), so I'm happy to spend some time testing things out & answering questions.

**Comment by SCWells72** [comment]
Okay, good news. You were correct earlier. I've confirmed that the issue here was in fact in IC2 itself where, in a small number of specific situations, it would perform type resolution from a reference point of the project source when it should have done so from a more restrictive reference point of the Salesforce system types. I've fixed those and everything resolves properly without any need for local type exclusions.

I'm still happy to push a branch (from a fork of your repo, of course) with an IC2 project already in place since I have it if you'd like. It would probably make sense to wait for next week's IC2 build that includes these fixes, though.

**Comment by jongpie** [comment]
@SCWells72 sorry for the late response, that's great to hear that you were able to make progress on this! If it's not a big inconvenience for you to push a branch, I'd love to take a look at it once the new IC2 release it available.

**Comment by jongpie** [comment]
Your Thursday morning release works out really nicely for me - this week is a little busy for me, but I usually don't have meetings Thursday afternoons, so I can try to take a look once you've done the public release (but I really appreciate the offer to provide an early build!). In the meantime, I'll take a quick peek at your fork's branches.

**Comment by SCWells72** [comment]
Sounds good. I imagine you've already found it, but just in case:

https://github.com/SCWells72/NebulaLogger

Once the new build is out on Thursday, I'll let you know of anything else you need to do to ensure the best experience with it.

**Comment by jongpie** [comment]
Awesome, thanks so much!

**Comment by SCWells72** [comment]
FYI, I found an issue while testing the build for today and want some additional test/burn-in time on the fix. Right now I'm thinking I'll release Monday morning, though it's possible I'll just push to next Thursday. I'll let you know as soon as it's ready, though.

**Comment by SCWells72** [comment]
Okay, the new IC2 build has been [released](https://illuminatedcloud.blogspot.com/2023/02/2255-release-notes.html). If/when you decide to play with it against your project--likely using branches listed below on [my fork](https://github.com/SCWells72/NebulaLogger)--here's the brain dump:

**Pre-reqs**

* Given the amount of JavaScript/ES6 in this project, a commercial JetBrains IDE is strongly recommended, e.g., WebStorm.
* If you want to use IC2's PMD integration, make sure that the PMD executable is in the system execution path. You can provide an explicit path to the PMD distribution on your system, but that results in the IDE project configuration containing a path outside of the project itself. Use of the system path allows portability of that config.

**Branches**

* `main` - Should be the exact same as yours. If you create a project from the `main` branch, IC2 will automatically set things up according to the `sfdx-project.json` file and walk you through selecting/creating a scratch org, generating an offline symbol table (OST) from the org, etc., to the point of a nicely functional project (see quirks/questions below, though).
* `ic2_minimal` - The end result of doing the above with a few additional things such as `.gitignore` entries to exclude the OST, unit test run configs for Apex and Jest, and an inspection (i.e., static code analysis) profile based on the standard IC2 profile but also configured to use the project's PMD ruleset. This and the branches below are pre-configured against an org with alias `Nebula_Logger_Base_Scratch_Org` which is the default based on `config/scratch-orgs/base-scratch-def.json`. If your org uses that same alias, all of the committed IDE project config should just work. No harm changing it as the config should catch up, but again, there are portability benefits from using a consistent alias.
`ic2_fixes` - The above with some small fixes to eliminate errors and false positives from a project-wide inspection run including typo fixes from the IDE's spellchecker. Even if nothing IC2 specific is interesting, it might be worth bringing some of these fixes back.
`ic2_fixes_formatters` - The above formatted against an included code style profile for all used languages that attempts to retain the overall code style of the existing project as closely as possible.

**Quirks/questions**

* If using a commercial JetBrains IDE, it will prompt you to run `npm install`. I've had trouble getting that to complete successfully against the project's `package.json` file--even directly from the command-line--due to the `chmod` usage in `prepare` (I'm on Windows) and due to a version conflict with `eslint`:
    ```
    npm ERR! Could not resolve dependency:
    npm ERR! peer eslint@"=8.8.0" from @ljharb/eslint-config@21.0.0
    npm ERR! node_modules/@ljharb/eslint-config
    npm ERR!   dev @ljharb/eslint-config@"latest" from the root project
    npm ERR!
    npm ERR! Conflicting peer dependency: eslint@8.8.0
    npm ERR! node_modules/eslint
    npm ERR!   peer eslint@"=8.8.0" from @ljharb/eslint-config@21.0.0
    npm ERR!   node_modules/@ljharb/eslint-config
    npm ERR!     dev @ljharb/eslint-config@"latest" from the root project
    ```
    Are those known issues?
* When this project is pushed to the org, it doesn't include `big-object-archiving` even though that's specified as a package directory in `sfdx-project.json`. I haven't looked at it enough to know why, but for the **All Apex Tests** unit test run config to complete successfully, those sources need to be pushed to the org. You can do so explicitly by right-clicking that directory and clicking **Illuminated Cloud > Deploy All Metadata**. Any idea why that doesn't happen, though?

I'm very happy to answer any questions you have and/or help you resolve any issues you encounter. Your project helped me to find and address several legitimate issues in IC2 I hadn't found in other projects, so I definitely want to pay that back a bit if possible! Just let me know.

**Comment by jongpie** [comment]
@SCWells72 so sorry for the delay! I had some home repair stuff come up recently & haven't had a chance to look at GitHub much over the last few weeks, but I'm hoping I'll have time at the end of this week to review this. Thanks so much for writing up your brain dump 🧠  - I'll follow up on your questions once I've tried it out. Glad to hear that this repo helped you find & resolve some IC2 issues, and looking forward to trying out IC2 myself!

**Comment by jongpie** [comment]
I'm closing this issue out since I don't think there are any changes needed. Let me know if you need anything else!
