### ISSUE TITLE
Logger: Log Creator permission set no longer needed after Summer '23

### ISSUE THREAD

**Issue by JeroenSfdc** [jongpie/NebulaLogger#441]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.9.0

### New Bug Summary

Not a big issue. 

I belief that the `Logger: Log Creator` permission set can be removed from the package (or mark it as obsolete in the description / label) / update the documentation. The majority of orgs have 'Disable Rules for Enforcing Explicit Access to Apex Classes (Release Update)' already silently being enabled (it will not show up in their Release Updates).

Excluding those customers who explicitly opted-in earlier on [Require User Access to Apex Classes Invoked by Flow](https://help.salesforce.com/s/articleView?id=release-notes.rn_automate_flow_release_update_require_user_access_to_apex_classes_invoked_by_flow.htm&type=5&release=242). For those the [release update to disable explicit access](https://help.salesforce.com/s/articleView?id=release-notes.rn_automate_flow_release_update_disable_apex_access_controls.htm&type=5&release=240) by Summer '23 will make the `Logger: Log Creator` effectively obsolete.

**Comment by jongpie** [comment]
@JeroenSfdc this is fantastic news, thanks for letting me know! I really hated having to deal with that release update a few years ago, and maintaining the `Logger: Log Creator` permission set adds a little extra maintenance work, so it'll be great to delete it. 

I'll plan to deprecate/delete the permission set as part of Nebula Logger's upcoming [Spring '23 release (`v4.10.0`)](https://github.com/jongpie/NebulaLogger/milestone/10) that I'm hoping to have released sometime in February.

**Comment by jongpie** [comment]
After some additional research on this, I think there are still some use cases for keeping the permission set `Logger: Log Creator` - for example, on Experience Cloud sites, the guest user profiles need to be given explicit access to Apex classes that are used in lightning components (which impacts the included `logger` LWC).

For now, I'll continue to maintain the permission set - I'll close this issue out for now, but happy to revisit this topic again if any other related changes are made to the platform.
