### ISSUE TITLE
Add more fields to the Log Entries search layout

### ISSUE THREAD

**Issue by solo-1234** [jongpie/NebulaLogger#443]
### New Feature Summary

When searching for log entries (eg: using an id of a record that was mentioned in a log), currently the only field that's displayed in the search results is the Entry Id. It would be useful if we could see some more info, such as the Log Name, Timestamp, and Logging Level. (I actually added them to the search layout myself but then the change was overwritten when I upgraded to a newer version of the package.)

Thanks!

**Comment by solo-1234** [comment]
Thanks!

**Comment by jongpie** [comment]
Ooof, @solo-1234 I just realized that almost none of the custom objects have descriptions either (screenshot below) - I'll add some descriptions to the objects too, I should have added it years ago 🤦 

![image](https://user-images.githubusercontent.com/1267157/214084559-981a5131-cf5c-4e06-b86e-e4602aa3b960.png)

**Comment by jongpie** [comment]
@solo-1234 I've released these changes as [v4.9.10](https://github.com/jongpie/NebulaLogger/releases/tag/v4.9.10)! Let me know if you run into any other issues or possible enhancements.

**Comment by solo-1234** [comment]
Thanks!
