### ISSUE TITLE
Null pointer Exception 

### ISSUE THREAD

**Issue by ramagrubhubGithub** [jongpie/NebulaLogger#447]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.7.8

### New Bug Summary

Getting a Null pointer Exception inside  ruleCriteriaMet(LogEntryEventHandler Class) when there is no value for the matching field(Log [Entry). We are using a Log Entry Tag rule based on the Origin__c field and when rule Criteria is excecuted it is having null value and comparison throwing a null pointer Exception.

**Comment by jongpie** [comment]
@ramagrubhubGithub thanks for reporting this! I think this is a fairly small bug - I'll try to fix this in one of the upcoming releases.
