### ISSUE TITLE
Error installing - Nebula Logger Added search result fields for all custom objects

### ISSUE THREAD

**Issue by MeStrak** [jongpie/NebulaLogger#458]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.9.10.1

### New Bug Summary

Hi there,

We're trying out Nebula logger and after trying to install on a Sandbox configured for our org we get an email saying that the installation failed.

We're installing with the following cli command, which works on a fresh scratch org:
`sfdx force:package:install --package "04t5Y0000015mv8QAA"`

Email is as follows:

> Subject: Sandbox: Package Nebula Logger Install Failed
> 
> CAUTION: This email originated from outside of your organization.
> 
> Your request to install package "Nebula Logger Added search result fields for all custom objects" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.
> 
> If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.
> 
> Organization: #### (####)
> User: #### (####)
> Package: Nebula Logger (04t5Y0000015mv8)
> 
> Problem:
> 
> 1.  Apex compile failure
> Apex class our_Chatbot_EventProcessor: line 27, column 57: Invalid type: ConversationDefinitionEventLog
> 
> 2.  Apex compile failure
> Apex class our_Chatbot_EventProcessor: line 31, column 20: Invalid type: Schema.ConversationDefinitionEventLog
> 
> 3.  Apex compile failure
> Apex class our_Chatbot_EventProcessor: line 65, column 9: Invalid type: ConversationDefinitionEventLog
> 
> 4.  Apex compile failure
> Apex class our_Chatbot_EventProcessor: line 68, column 14: Invalid type: ConversationDefinitionEventLog
> 
> ....

125 errors in total - they are all related to chatbot classes.

I'm not sure if it's a coincidence but it really sticks out to me that the first errors reported are related to ConversationDefinition**EventLog** (https://help.salesforce.com/s/articleView?id=sf.bots_service_data_reference.htm&type=5). I'm wondering if it could be a conflict between the two as we're using the unlocked package which is not namespaced.

Any insights would be appreciated 😄 

Thanks!

**Comment by jamessimone** [comment]
@MeStrak I would try using that same command but with the Apex compile setting tuned to package only: `sfdx force:package:install --package "04t5Y0000015mv8QAA" -a package`.

**Comment by jongpie** [comment]
@MeStrak I agree with @jamessimone, try using the `-a package` parameter. In this case, I think that the error being in regards to an object with the work `Log` in it is purely coincidental, there's no metadata in Nebula Logger with the name `ConversationDefinitionEventLog`. This sounds like a setting in your org has changed and that object is no longer available in your org, I don't think it has anything to do with Nebula Logger.

**Comment by jongpie** [comment]
Whoops! Didn't mean to close this yet - I'll keep this open until @MeStrak can confirm that it's definitely not an issue with Nebula Logger's unlocked packages.

**Comment by MeStrak** [comment]
Thanks @jamessimone and @jongpie - you were spot on with this. The proposed `-a package` argument worked, and this was due to an issue in the specific sandbox we were trying the installation in. I'll close this issue - you can expect a PR from someone in our team to add the CLI command to the docs 😄 

We ❤️ Nebula Logger by the way, assuming our testing goes well I'm hoping to have it setup in our org within the next few weeks.

**Comment by jongpie** [comment]
@MeStrak I'm glad to hear that it worked, and that your team loves Nebula Logger! ♥️

If any other questions or issues come up during your testing, please let us know!

**Comment by jongpie** [comment]
@MeStrak I was thinking about this a little more - I think it's a great idea to provide the CLI commands for installing the packages. Personally, I always install packages via the CLI, so I'm not sure why I haven't previously included in the commands anywhere in the docs 😅 

Moving forward, I'll plan to include the `sfdx` package install commands (including the `-a package` parameter) in [the release notes](https://github.com/jongpie/NebulaLogger/releases) for all future releases - that way, you can just copy/paste the exact command needed to install particular version.

**Comment by MeStrak** [comment]
> @MeStrak I was thinking about this a little more - I think it's a great idea to provide the CLI commands for installing the packages. Personally, I always install packages via the CLI, so I'm not sure why I haven't previously included in the commands anywhere in the docs 😅
> 
> Moving forward, I'll plan to include the `sfdx` package install commands (including the `-a package` parameter) in [the release notes](https://github.com/jongpie/NebulaLogger/releases) for all future releases - that way, you can just copy/paste the exact command needed to install particular version.

Sounds great!
