### ISSUE TITLE
Apex Logging mechanism is not working!

### ISSUE THREAD

**Issue by sarat-vs** [jongpie/NebulaLogger#467]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.9.11

### New Bug Summary

Hello @jongpie / Hello All,

Today I updated from v4.6.14 to v4.9.11 and performed some tests. Unfortunately there are no Logs getting generated or created in the logger console. 
I did checked and compared all the permission sets and custom setting. I didn't find much impactful difference.

Currently, I use the following code for logging the error:

try{
-code-
}catch(Exception e){
Logger.error('Error on classname' +e);
Logger.error('Method: MethodName()').parseStackTrace(e.getStackTraceString());
Logger.saveLog();
}

Can you please advise me if I have to modify anything else to get the proper logs in the console?

Thanks in advance.

**Comment by jongpie** [comment]
Hi @sarat-vs - there have been several changes between `v4.6.14` and `v4.9.11`, so I'm not 100% sure what could be causing the issue, but there are a few things you can try:

- Try running this script to see if it throws any errors
  ```java
  Logger.info('testing logging, using synchronous DML', Logger.getUserSettings());
  Logger.saveLog(Logger.SaveMethod.SYNCHRONOUS_DML);
  ```
- Try deleting any records in `LoggerSettings__c` and run this script - there have been some field changes to the `LoggerSettings__c` object, so it's possible some of your existing records are causing the issue.
  ```java
  Logger.info('testing logging, using default settings', Logger.getUserSettings());
  Logger.saveLog();
  ```

Let me know if either of those scripts result in logs properly being generated.

**Comment by sarat-vs** [comment]
Hello @jongpie ,

Thanks, great , it worked!

The "Enable Saving"  was unchecked. I made it to "checked" and now all the logging works fine. 

<img width="574" alt="image" src="https://user-images.githubusercontent.com/110805443/227532026-60e1098b-ed7b-4173-9638-52b702a29f98.png">

Can you please add the same in **upgrade notes**, so that anyone can look into and fix them!

**Comment by jongpie** [comment]
Hi @sarat-vs - I try to mention these types of breaking changes in the release notes. In this case, [the release notes for `v4.7.0`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.7.0) state that if you're upgrading, you'll need to make changes to `LoggerSettings__c` records after upgrading. I recommend reviewing the release notes prior to upgrading in the future.

![image](https://user-images.githubusercontent.com/1267157/227752125-eab0e287-4924-451b-9322-52868e5992f8.png)
