### ISSUE TITLE
Tests failing due to lack of "Automated Process" user

### ISSUE THREAD

**Issue by YodaDaCoda** [jongpie/NebulaLogger#469]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.9.11

### New Bug Summary

The following tests fail when there is no User with the name "Automated Process". Based on my investigation in my new orgs (created late 2022), the Automated Process User now gets the name "Platform Integration User" - but there's two other Users with the same Name.

https://github.com/jongpie/NebulaLogger/blob/46ddff19e0628021f354a1e112d054ac70120d5b/nebula-logger/core/tests/log-management/classes/LogEntryEventHandler_Tests.cls#L444

https://github.com/jongpie/NebulaLogger/blob/46ddff19e0628021f354a1e112d054ac70120d5b/nebula-logger/core/tests/log-management/classes/LogEntryEventHandler_Tests.cls#L466

Based on my investigation, the best way to handle this is to filter on Username instead - replace the `WHERE` condition in these tests with something like `WHERE Username = :('autoproc@' + UserInfo.getOrganizationId())`

Happy to create a PR if appropriate. 😄

**Comment by jongpie** [comment]
@YodaDaCoda thanks for reporting this! I haven't come across this issue yet in my orgs (Salesforce is probably slowly rolling out this change), but I love your approach for querying on the username, that seems like a more reliable approach.

I'm wrapping up the next release right now (PR #465), so I can include this bugfix in that PR. I should have the next release finished sometime this week.

**Comment by jongpie** [comment]
@YodaDaCoda this has been implemented in [`v4.10.01](https://github.com/jongpie/NebulaLogger/releases/tag/v4.10.0). Let me know if you run into any other issues!
