### ISSUE TITLE
Ability to capture logs in LWC wire method

### ISSUE THREAD

**Issue by rguttikondaSFDC** [jongpie/NebulaLogger#483]
### New Feature Summary

I am trying to capture errors in an LWC wire method 
for ex: My LWC component fetches data from a Contact record and if I do not have access to the field I want to capture this using Nebula Logger. 

Currently I am unable to do it as the child (logger) wire method is not completed by the time the error occurs in the parent.

**Comment by jongpie** [comment]
@rguttikondaSFDC this should now be possible in [the new `v4.10.2` release](https://github.com/jongpie/NebulaLogger/releases/tag/v4.10.2) - this release includes some changes to how you use the `logger` LWC in your component, which then provides support for logging in wire methods.
