### ISSUE TITLE
It seems that my Logger Setting isn't respected in apex tests

### ISSUE THREAD

**Issue by solo-1234** [jongpie/NebulaLogger#487]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.9.9

### New Bug Summary

It seems that my Logger Setting record isn't respected in apex tests. 

I have a couple of tests that are failing due to `Apex CPU time limit exceeded` 

Stack trace:
```
Class.LogEntryEventBuilder.<init>: line 114, column 1
Class.Logger.newEntry: line 2934, column 1
Class.Logger.newEntry: line 2930, column 1
Class.Logger.debug: line 2914, column 1
Class.Logger.debug: line 1631, column 1
etc etc
```

In my Logger Setting record (which the only one, set to Organization) I tried changing the Log Level to WARN but still received the error, so then I unchecked the Enabled checkbox and still receive the error.

Any idea how to troubleshoot this further? Thanks!

**Comment by jongpie** [comment]
Hey @solo-1234! Just to clarify on this, are you creating your Logger Setting record directly within your test? `LoggerSettings__c` records are considered data (not metadata), so during Apex tests, the settings records configured in your org won't be used - you'll have to configure the `LoggerSettings__c` within your tests in order to disable logging during the test execution. You could do something like this:

```java
@IsTest
private static void runsSomeTest() {
  LoggerSettings__c settings = LoggerSettings__c.getOrgDefaults();
  settings.IsEnabled__c = false;
  upsert settings;
  // TODO add the rest of your test here - logging will now be disabled in this test method
}
```

**Comment by solo-1234** [comment]
I am not creating the settings within the test. That would explain it! Is even the Org Default record hidden during tests? If so, how does Logger know what settings to fall back to?

**Comment by solo-1234** [comment]
I added a TestSetup method to change the logging level to INFO and now they all passed. Thanks!

**Comment by jongpie** [comment]
@solo-1234 that's great, glad to hear that they're passing now! And when you don't have any `LoggerSettings__c` records created (including during Apex tests that don't create a record), Logger will automatically create an in-memory `LoggerSettings__c` records that uses the default field values (based on how I've configured each field on `LoggerSettings__c`.

Let me know if you need anything else!

**Comment by solo-1234** [comment]
Thanks for those details! That explains why my tests started failing when the default Logging Level was changed to FINEST.
