### ISSUE TITLE
Installation Failing

### ISSUE THREAD

**Issue by oakyraja** [jongpie/NebulaLogger#504]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.10.5

### New Bug Summary

On Installation the following error is observed : 
sfdx package install --wait 20 --security-type AdminsOnly --package 04t5Y0000023SCHQA2
? This package might send or receive data from these third-party websites:

[api.status.salesforce.com]

Grant access (y/n)? Yes
Waiting 20 minutes for package install to complete.... done
Error (1): Encountered errors installing the package! Installation errors:
1) Dependent class is invalid and needs recompilation:  Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:  Class LogHandler : Invalid type: Log__Share, Details: FlowCollectionLogEntry_Tests: Dependent class is invalid and needs recompilation:  Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:  Class LogHandler : Invalid type: Log__Share

<img width="724" alt="image" src="https://github.com/jongpie/NebulaLogger/assets/132605371/a292ffdb-a458-46ad-b9a9-e428846f610d">

**Comment by oakyraja** [comment]
This is the error i got in email : 

1.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
FlowCollectionLogEntry_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

2.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
FlowLogEntry_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

3.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
FlowLogger_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

4.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
FlowRecordLogEntry_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

5.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
LogBatchPurgeController_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

6.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
LogBatchPurgeScheduler_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

7.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
LogBatchPurger_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

8.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
LogEntryEventHandler_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

9.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
LogEntryEventStreamController_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

10.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
LogEntryHandler_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

11.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
LogEntryTagHandler_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

12.  Invalid type: Log__Share
LogHandler: Invalid type: Log__Share

13.  Invalid type: Log__Share
LogHandler: Invalid type: Log__Share

14.  Variable does not exist: logShares
LogHandler: Variable does not exist: logShares

15.  Method does not exist or incorrect signature: void insertRecords(List<Log__Share>, Boolean) from the type LoggerDataStore.Database
LogHandler: Method does not exist or incorrect signature: void insertRecords(List<Log__Share>, Boolean) from the type LoggerDataStore.Database

16.  Invalid type: Log__Share
LogHandler_Tests: Invalid type: Log__Share

17.  Variable does not exist: logShares
LogHandler_Tests: Variable does not exist: logShares

18.  Method does not exist or incorrect signature: void serializePretty(List<Log__Share>) from the type System.JSON
LogHandler_Tests: Method does not exist or incorrect signature: void serializePretty(List<Log__Share>) from the type System.JSON

19.  Variable does not exist: logShares
LogHandler_Tests: Variable does not exist: logShares

20.  Variable does not exist: logShares
LogHandler_Tests: Variable does not exist: logShares

21.  Variable does not exist: Schema.Log__Share.RowCause
LogHandler_Tests: Variable does not exist: Schema.Log__Share.RowCause

22.  Variable does not exist: logShares
LogHandler_Tests: Variable does not exist: logShares

23.  Variable does not exist: logShares
LogHandler_Tests: Variable does not exist: logShares

24.  Invalid type: Log__Share
LogHandler_Tests: Invalid type: Log__Share

25.  Variable does not exist: logShares
LogHandler_Tests: Variable does not exist: logShares

26.  Method does not exist or incorrect signature: void serializePretty(List<Log__Share>) from the type System.JSON
LogHandler_Tests: Method does not exist or incorrect signature: void serializePretty(List<Log__Share>) from the type System.JSON

27.  Variable does not exist: logShares
LogHandler_Tests: Variable does not exist: logShares

28.  Variable does not exist: logShares
LogHandler_Tests: Variable does not exist: logShares

29.  Variable does not exist: Schema.Log__Share.RowCause
LogHandler_Tests: Variable does not exist: Schema.Log__Share.RowCause

30.  Variable does not exist: logShares
LogHandler_Tests: Variable does not exist: logShares

31.  Variable does not exist: logShares
LogHandler_Tests: Variable does not exist: logShares

32.  Invalid type: Log__Share
LogHandler_Tests: Invalid type: Log__Share

33.  Variable does not exist: logShares
LogHandler_Tests: Variable does not exist: logShares

34.  Method does not exist or incorrect signature: void serializePretty(List<Log__Share>) from the type System.JSON
LogHandler_Tests: Method does not exist or incorrect signature: void serializePretty(List<Log__Share>) from the type System.JSON

35.  Invalid type: Log__Share
LogHandler_Tests: Invalid type: Log__Share

36.  Variable does not exist: logShares
LogHandler_Tests: Variable does not exist: logShares

37.  Method does not exist or incorrect signature: void serializePretty(List<Log__Share>) from the type System.JSON
LogHandler_Tests: Method does not exist or incorrect signature: void serializePretty(List<Log__Share>) from the type System.JSON

38.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
LogManagementDataSelector_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

39.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
LoggerEmailSender_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

40.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
LoggerScenarioHandler_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

41.  Variable does not exist: Schema.Log__Share.AccessLevel
LoggerSettingsController: Variable does not exist: Schema.Log__Share.AccessLevel

42.  Variable does not exist: Schema.Log__Share.AccessLevel
LoggerSettingsController_Tests: Variable does not exist: Schema.Log__Share.AccessLevel

43.  Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
LoggerTagHandler_Tests: Dependent class is invalid and needs recompilation:
 Class LoggerTestConfigurator : Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

44.  Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share
LoggerTestConfigurator: Dependent class is invalid and needs recompilation:
 Class LogHandler : Invalid type: Log__Share

45.  Invalid type: LogHandler
Log: Invalid type: LogHandler

46. (LoggerCore) No classes found for FlowCollectionLogEntry_Tests.
LoggerCore: No classes found for FlowCollectionLogEntry_Tests.

47. (loggerSettings) Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
loggerSettings: Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.

48. (loggerSettings) Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
loggerSettings: Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.

49. (loggerSettings) Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
loggerSettings: Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.

50. (loggerSettings) Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
loggerSettings: Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.

51. (loggerSettings) Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
loggerSettings: Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.

52. (loggerSettings) Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
loggerSettings: Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.

53. (loggerSettings) Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
loggerSettings: Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.

54. (loggerSettings) Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
loggerSettings: Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.
Unable to find Apex action class referenced as 'LoggerSettingsController'.

55. (LoggerAdmin) In field: apexClass - no ApexClass named LoggerSettingsController found
LoggerAdmin: In field: apexClass - no ApexClass named LoggerSettingsController found

56. (LoggerLogViewer) In field: apexClass - no ApexClass named LoggerSettingsController found
LoggerLogViewer: In field: apexClass - no ApexClass named LoggerSettingsController found

**Comment by jongpie** [comment]
Hi @oakyraja - is there any chance that your org has an existing object named `Log__c`? I've seen this error [one other time](https://github.com/jongpie/NebulaLogger/issues/470), and in that case, the issue was due to existing metadata in the org conflicting with the metadata in the unlocked package.

**Comment by oakyraja** [comment]
Yup @jongpie , That's exactly the issue. I was able to install the managed package but Unlocked Was failing.
We had a Custom Object named Log__c which we were not using extensively. I deleted that in my dev sandbox and was able to install the unlocked package.

Thanks for the expert tip 👍

**Comment by jongpie** [comment]
@oakyraja glad to hear that worked! Let me know if you run into any other issues or questions.
