### ISSUE TITLE
Get Environment Type in Apex

### ISSUE THREAD

**Issue by jonny-harte** [jongpie/NebulaLogger#510]
### New Feature Summary

Is it possible to get the Environment Type in Apex? I'm trying to reduce the amount of debug logs we have in production and would like to conditionally create them only in sandboxes.

**Comment by jamessimone** [comment]
@jongpie can weigh in further, but typically we handle this through configuration - eg, your Logger Settings are configured in your sandbox to log at the finest level, whereas in production you might only actually log warnings and errors. I'd advise against conditionally hating your logging code by something like environment - that will clutter it up and the Logger Settings record(s) are really the ideal way to control this.

**Comment by jamessimone** [comment]
Awesome - glad to be able to help!
