### ISSUE TITLE
Populate HTTP Fields on LogEntry__c

### ISSUE THREAD

**Issue by jonny-harte** [jongpie/NebulaLogger#513]
### New Feature Summary

Hi, when are the HTTP Request & Response fields used and how can I populate them?

I'd like to create log entries for callouts to capture the requests and responses both in Apex and Flow but I can't find any documentation or example on how to populate these fields.

**Comment by jamessimone** [comment]
Calls to the base `Logger` methods - like `Logger.debug` return an instance of `LogEntryEventBuilder`. It's this builder instance that can take in the request/response details (which end up setting those fields):

```java
Logger.error('Error while contacting some API').setHttpResponseDetails(yourHttpResponse).setHttpRequestDetails(yourHttpRequest);
```
