### ISSUE TITLE
Convert "View JSON" aura component to LWC

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#54]
We might still need an aura component as a wrapper (since it's a quick action), but the current component should be converted to LWC

**Comment by jamessimone** [comment]
Happy to take this on after spring21 is GA - LWC can be used with quick actions natively in just a few weeks!

**Comment by jongpie** [comment]
Ooooh, really?? I was planning to release the managed package with the aura component, not realizing that LWC will finally be supported in quick actions - that's exciting news! I'd love to get it converted before releasing the managed package. At this point, my plan is to create a Spring '21 release (with a few minor enhancements + cleanup), which will hopefully be released as the managed package.

Feel free to take over this issue if you're interested!

**Comment by jamessimone** [comment]
yeah, I can start working on it in the coming days using a pre-release scratch org. Happy to take this one on!

**Comment by jongpie** [comment]
@jamessimone I'm planning to go ahead and remove the aura component and remove the method `Logger.getLog(Id recordId)` (to get ready for a managed package release). Whenever you create the replacement lwc, I think it probably makes sense to create a separate, dedicated Apex controller class for the component (instead of awkwardly using `Logger` as the Apex controller like I've been doing with the aura component) - let me know what you think.
