### ISSUE TITLE
Bulk Logs Handling

### ISSUE THREAD

**Issue by Charush-Devgan-EF** [jongpie/NebulaLogger#541]
### New Feature Summary

Hi, as I saw that at the end we need to save it by using logger.saveLog() statement. But let's say we have the logic to be logged into a separate class which is being called in loop from  a batchable or queueable job and we need to save the collection of logs all together not one by one. Is there a way to handle such kind of scenarios?

**Comment by jongpie** [comment]
Hi @Charush-Devgan-EF - the best way to handle that scenario would be to call `Logger.saveLog()` after your loop (instead of inside the loop).  Using `Logger.saveLog()` should be treated like a DML statement or SOQL query, in that you shouldn't use them inside of a loop. If you have an example of your code (or pseudo-code), I'm happy to take a look and give more specific suggestions on when/where to call `Logger.saveLog()`

**Comment by Charush-Devgan-EF** [comment]
Hi @jongpie let me give you a code snippet -

public class BatchClass implements Database.batchable {
  public List<sObject> start(Database.BatchableContext BC) {
        return Database.query('Some query');
  }

  public void execute(Database.BatchableContext BC, List<sObject> scope) {
    IntegrationClass intRef;
    for(sObject objRec: scope) {
      intRef = new IntegrationClass()
      intRef.sendData(objRec);
    }
    /*
    I want to collect all logs from Integration class 
    in Batch class and save all at once because if I save it in 
    Integation class then It's not bulkfied.
    */
  }

  public void finish(Database.BatchableContext BC) {}  

} 

public class IntegrationClass {
  
  public void sendData(sObject record) {
    Logger.debug('Add log entry using Nebula Logger with logging level == DEBUG');
    Logger.info('Add log entry using Nebula Logger with logging level == INFO');
  }

}

**Comment by jongpie** [comment]
@Charush-Devgan-EF based on that example, you just need to add `Logger.saveLog()` after the `for` loop (where you have your comment):

```apex
public class BatchClass implements Database.batchable {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('Some query');
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        for(sObject objRec : scope) {
            IntegrationClass intRef = new IntegrationClass();
            intRef.sendData(objRec);
        }
        /*
        I want to collect all logs from Integration class
        in Batch class and save all at once because if I save it in
        Integation class then It's not bulkfied.
        */
        
        /* 
        The Logger class handles collecting all log entries from the current transaction.
        You can just call saveLog() to save them.
        */
        Logger.saveLog();
    }

    public void finish(Database.BatchableContext bc) {}

    public class IntegrationClass {
        public void sendData(sObject record) {
            Logger.debug('Add log entry using Nebula Logger with logging level == DEBUG');
            Logger.info('Add log entry using Nebula Logger with logging level == INFO');
        }
    }
}
```

**Comment by jongpie** [comment]
No problem! I'm closing this issue, but let me know if you have other questioms
