### ISSUE TITLE
Usernames on Log Entry Summary Report show up in an HTML Tag

### ISSUE THREAD

**Issue by Senay-Ersen** [jongpie/NebulaLogger#543]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.11.0

### New Bug Summary

Hi,
As shown in the screen shot below, the usernames on Log Entry Summary Report shows up in an HTML Tag. It is not a major issue but needs to be fixed I think. 

Thank you.

![LogEntrySummary_userName](https://github.com/jongpie/NebulaLogger/assets/126723243/c4a3d41c-2e5c-4407-bfe3-7bc7ae382b22)

**Comment by jongpie** [comment]
@Senay-Ersen thanks for reporting this! I completely agree, it's not major, but this needs to be addressed. I'll see what options there are to address - if it can't be fixed directly in the report, I might add a new formula field that doesn't include any HTML.

**Comment by JMercie** [comment]
I created a PR to aim to fix this (#567) 

It looks like this was reported as [known issue back in 2018](https://issues.salesforce.com/issue/a028c00000qQ2ULAA0/report-chart-displays-formula-text-instead-of-returned-value) and it is in [the idea exchange](https://ideas.salesforce.com/s/idea/a0B8W00000GdnGgUAJ/report-chart-or-exported-report-displays-formula-hyperlink-text) to be implemented.

There's also [a help article](https://help.salesforce.com/s/articleView?id=000394024&type=1) that addresses the workaround for the issue that I use as a guide for the PR submitted for this.

**Comment by jongpie** [comment]
@Senay-Ersen this has been fixed in [release `v4.11.9`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.11.9). Thanks again for reporting the issue, and thanks to @JMercie for fixing it!
