### ISSUE TITLE
Use Logger in LWC via import instead of using in template

### ISSUE THREAD

**Issue by JackVeromeev** [jongpie/NebulaLogger#544]
### New Feature Summary

Hi!

_Sorry if the feature was already mentioned._

I have just started investigating Logger! First of all, it's an awesome tool! I just wanted to ask if it would be possible to use the logger functionality in LWC without creating the component in the template.
E.g.

```javascript
import {logger} from 'nebula/logger';
// ...
logger.info("test");
```

Are there limitations on porting it in the importable lib?

**Comment by jamessimone** [comment]
See #494 for more info on this feature - you can already do so today!
