### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by ctcforce** [jongpie/NebulaLogger#549]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

n/a

### New Bug Summary

_Within App Builder, admins can add the 'Related Log Entries' lightning web component (lwc) to any record page. Admins can also control which columns are displayed_ **be** _creating & selecting a field set on LogEntry__c with the desired fields._

**be** => **by**

**Comment by jongpie** [comment]
Thanks for the feedback! This is fixed now.
