### ISSUE TITLE
System.AsyncException: Future method cannot be called from a future or batch method: Nebula.LogEntryEventHandler.setStatusApiDetails()

### ISSUE THREAD

**Issue by mittahari** [jongpie/NebulaLogger#550]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.6.0

### New Bug Summary

Used Nebula Logger in Apex Batch class and getting error at the time of saving the logs during batch execution. For testing purpose, created Batch Apex class provided as an example in the github page. Even though having the same issue.
Class Name : BatchableLoggerExample
Error: System.AsyncException: Future method cannot be called from a future or batch method: 
Nebula.LogEntryEventHandler.setStatusApiDetails()
Request to review the attached logs. Hoping for quick resolution since we have used Nebula Logger in many classes which are being failed. 
[apex-07L7X00000KJd5sUAD.log](https://github.com/jongpie/NebulaLogger/files/12642381/apex-07L7X00000KJd5sUAD.log)
Thanks in advance! @jongpie

**Comment by jongpie** [comment]
Hi @mittahari - in your org, do you know what value is being used in the custom settings field `LoggerSettings.DefaultSaveMethod__c`? Typically, that method would not be triggered directly when running a batchable, so I'm wondering if the settings in your org are causing an issue.

Long-term, I think you'll want to upgrade to a newer version of Nebula Logger - that `@future` method has been removed in newer versions, and there is also now a custom metadata type, `LoggerParameter__mdt`, that would let you disable this integration (as well as have more control overall).

**Comment by mittahari** [comment]
Hi @jongpie,
"LoggerSettings.DefaultSaveMethod__c = SYNCHRONOUS_DML" - In default Org settings record - Didn't work
"LoggerSettings.DefaultSaveMethod__c = EVENT_BUS" - In User settings record - Working fine
So, does the field (LoggerSettings.DefaultSaveMethod__c) value should be "EVENT_BUS"?

**One more:** I see that SaveLog() is treated non-setup object DML. In my case, I'm updating user and trying to log the success & error logs. But unable to process with this error "System.DmlException: Upsert failed. First exception on row 0; first error: MIXED_DML_OPERATION, DML operation on setup object is not permitted after you have updated a non-setup object (or vice versa): Nebula__Log__c, original object: User: []". Is there any alternative to track the logs on performing dml on user/any setup object? 
Thanks!

**Comment by jongpie** [comment]
Hi @mittahari - in general, "EVENT_BUS" is the recommended value for `LoggerSettings.DefaultSaveMethod__c`. This value will use [the `EventBus` class in Apex](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_eventbus.htm), which has a daily limit that you'll want to consider, but it's the most reliable option for saving logging data.

When you're encountering the `MIXED_DML_OPERATION` exception, what value is being used for `LoggerSettings.DefaultSaveMethod__c`?

**Comment by mittahari** [comment]
Got the issue resolved by updating "LoggerSettings.DefaultSaveMethod__c" field to EVENT_BUS. Thank you! @jongpie

**Comment by jongpie** [comment]
Awesome, glad to hear it! If you run into any other issues or questions, just let me know.
