### ISSUE TITLE
EntryScenarioName__c is blank on Log Entries

### ISSUE THREAD

**Issue by solo-1234** [jongpie/NebulaLogger#571]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.11.9	

### New Bug Summary

I just tried using Entry Scenario Name but it seems to be blank on all log entry records, even those that have a log scenario set (via flow or apex). What's interesting is that Entry Scenario Link is populated.

![image](https://github.com/jongpie/NebulaLogger/assets/59446952/11d90564-2917-41ca-b8d9-bcc4ccb5a0ce)

**Comment by jongpie** [comment]
@solo-1234 I've just released some new formula fields for this in [the latest release, `v4.12.0`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.12.0). Thanks again for all your feedback - let me know if you need anything else!

**Comment by solo-1234** [comment]
That's great - thank you!
