### ISSUE TITLE
Error STRING_TOO_LONG on HttpRequestEndpoint__c field

### ISSUE THREAD

**Issue by BastienRaoul** [jongpie/NebulaLogger#589]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.7.8

### New Bug Summary

Hello @jongpie,

A `STRING_TOO_LONG` error can occur on HttpRequestEndpoint__c field if the HTTP request endpoint is longer than 255 characters, which can easily be the case if the endpoint takes multiple parameters.

**Comment by jongpie** [comment]
@BastienRaoul this should now be fixed [in the new release `v4.12.6`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.12.6). I've updated the class `LoggerDataStore.EventBus` to automatically truncate values when publishing `LogEntryEvent__e` records. This should solve the `STRING_TOO_LONG` error for `HttpRequestEndpoint__c` in particular, as well as any other string field.

If you run into any other issues, let me know!

**Comment by adepew** [comment]
> @BastienRaoul this should now be fixed [in the new release `v4.12.6`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.12.6). I've updated the class `LoggerDataStore.EventBus` to automatically truncate values when publishing `LogEntryEvent__e` records. This should solve the `STRING_TOO_LONG` error for `HttpRequestEndpoint__c` in particular, as well as any other string field.
> 
> If you run into any other issues, let me know!

I wasn't sure to open a new issue or reply to this one. However, I am on package version 4.13.6 and am getting this error message for the Message__c field..

![image](https://github.com/jongpie/NebulaLogger/assets/30325923/806e089d-0073-4f2b-87e9-3d9f88530c66)

**Comment by jongpie** [comment]
@adepew I'm having trouble recreating the issue with the `Message__c` using `v4.13.6` - I'm running this anonymous Apex script, and it seems to properly truncate the string every time.

```apex
Logger.info('A'.repeat(LogEntryEvent__e.Message__c.getDescribe().getLength() + 1));
Logger.saveLog(Logger.SaveMethod.SYNCHRONOUS_DML);
```

Is there any chance you're using some custom data mask rules (stored in `LogEntryDataMaskRule__mdt`)? Those could be causing the `STRING_TOO_LONG` error to still happen.

**Comment by adepew** [comment]
> @adepew I'm having trouble recreating the issue with the `Message__c` using `v4.13.6` - I'm running this anonymous Apex script, and it seems to properly truncate the string every time.
> 
> ```apex
> Logger.info('A'.repeat(LogEntryEvent__e.Message__c.getDescribe().getLength() + 1));
> Logger.saveLog(Logger.SaveMethod.SYNCHRONOUS_DML);
> ```
> 
> Is there any chance you're using some custom data mask rules (stored in `LogEntryDataMaskRule__mdt`)? Those could be causing the `STRING_TOO_LONG` error to still happen.

I don't have anything in LogEntryDataMaskRule__mdt except for a Visa/MC and SSN mask that appear to have been created with the package. However, it does appear to be something with our integration to 6Sense as it's coming from my 6Sense integration user. I'm going to log that user to see if I can get any more details for you.

**Comment by jamessimone** [comment]
@adepew is there any chance that you can give us a bit more info about the code that's causing this error to occur? e.g. the code snippet where you're using Logger in such a way that causes the error email to be sent? Thanks so much!
