### ISSUE TITLE
Related Log Entries : Admins Need to manually select Log Entry Field Set value. 

### ISSUE THREAD

**Issue by shreyas-girjapure** [jongpie/NebulaLogger#596]
### New Feature Summary

As a new admin user for Nebula logger , When tried to add Related Log entries component on flexi page. Component wasn't showing related records although there were some.

![image](https://github.com/jongpie/NebulaLogger/assets/66116603/651fc0a2-ab62-440b-9699-17d8f0fe7354)

Admins need to manually select either default value or any value of their choice.

Since there is already a `Related List Defaults` field set created.

We should set it as default value when admins use component on their page. Later they may select other field set values if they wishes so.

**Comment by shreyas-girjapure** [comment]
😑 actually i worked on it but forgot to raise PR. Let me know if you need help in that

**Comment by jongpie** [comment]
@shreyas-girjapure no worries! I've got a PR ready for this change (PR #602), I'm just trying to solve 1 unrelated pipeline issue. I'm hoping I can get it released today (or worst case, on Monday).

**Comment by jongpie** [comment]
@shreyas-girjapure this is [now available in `v4.12.2`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.12.2) 🥳 Thanks again for the suggestion, and let me know if you have any other feedback!
