### ISSUE TITLE
setTransactionQuiddity throws error executing UserInfo.getSessionId()

### ISSUE THREAD

**Issue by dvanlooy** [jongpie/NebulaLogger#598]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.8.2

### New Bug Summary

When a user which is logged in through a (server-to-server) connected app with setting "Issue JSON Web Token (JWT)-based access tokens for named users" true tries to use a Logger.xxx method, a Salesforce System Error is thrown.
Debugging learns that these actions fail on calling System.UserInfo.getSessionId() (used in Logger.setTransactionQuiddity).
Current bypass is to set "Issue JSON Web Token (JWT)-based access tokens for named users" false, or to add try/catch arround System.UserInfo.getSessionId().
<img width="626" alt="Screenshot 2024-01-18 at 11 16 37" src="https://github.com/jongpie/NebulaLogger/assets/17290962/a134d4dd-4b9f-4265-9d2c-40fb31780cbb">
<img width="325" alt="Screenshot 2024-01-18 at 10 48 20" src="https://github.com/jongpie/NebulaLogger/assets/17290962/4f3a1094-5e48-4815-9ac7-13f7ab7f49ca">

<img width="1358" alt="Screenshot 2024-01-18 at 11 05 22" src="https://github.com/jongpie/NebulaLogger/assets/17290962/90120ac0-db5b-4b9a-87c0-6b6a90eba9d3">

**Comment by jongpie** [comment]
@dvanlooy thanks for reporting this! @jamessimone and I have made several attempts at trying to work around some of the issues related to sessions, it seems like the fun never ends! 😅 

It looks like you're on an older version of Nebula Logger, but even in the newer versions, it's still relying on `System.UserInfo.getSessionId()` - I like your idea of adding a try/catch around it, that should be fairly simple to implement. I'll work on getting this changed ASAP.

**Comment by jongpie** [comment]
@dvanlooy I've just released changes for this [in release `v4.12.3`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.12.3). Once you're able to upgrade & test it out, please let me know if you run into any more issues!
