### ISSUE TITLE
Capture OrgLimits data on Log__c

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#630]
Currently, the `LogEntry__c` object has multiple fields related to tracking _transactional_ limits, [using the class `System.Limits`](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm). I think it'd be helpful to capture and store _organizational_ limits on `Log__c`, [using the class `System.OrgLimits`](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_System_OrgLimit.htm#apex_class_System_OrgLimit). 

This data would probably need to be stored in a long text-area field (as JSON) and displayed using a custom component - the values returned by `OrgLimits` can be drastically different between orgs, based on the orgs licenses & add-ons, so it's not feasible to have a predefined number of fields on `Log__c`. This means that things like standard reports & dashboards probably can't be used to view this data, but using a custom component would at least provide admins/devs with a way to see the information.

**Comment by jongpie** [comment]
@jamessimone that's great to know, because that sounds... terribly frustrating 😅 I'm trying to think of a rational explanation for why the `OrgLimits` would work that way, but I'm guessing there's not a very satisfying answer. Sounds like a stub will definitely be needed!

**Comment by jamessimone** [comment]
Haha yeah. Here're [the relevant lines](https://github.com/jamessimone/apex-rollup/blob/main/rollup/core/classes/RollupLimits.cls#L23-L40) in the codebase and [the test that uses the stub](https://github.com/jamessimone/apex-rollup/blob/main/extra-tests/classes/RollupTests.cls#L3031-L3045)!

**Comment by jongpie** [comment]
This is now available in [release `v4.13.2`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.13.2) 🎉
