### ISSUE TITLE
Flow Faults Not Logging

### ISSUE THREAD

**Issue by ryanwischnefski** [jongpie/NebulaLogger#643]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.13.1

### New Bug Summary

Hi!

We are using the framework extensively in our code and are looking to add this to our flows. We were testing using debug and saw it was triggered and working. When we go to test in the UI, it does not create any actual logs that I can see.

I have reviewed the debug logs, and noted the debug where it shows the transaction Id from Nebula logger but when I again search for that in the log or log entry event ID nothing shows.

Am I doing something wrong when it comes to adding this to flows? I have attached screenshots to show the configuration in question to help. Thank you! 

![image](https://github.com/jongpie/NebulaLogger/assets/137924470/e524db10-7abc-4abe-8fb0-7a066ba712e2)
![image](https://github.com/jongpie/NebulaLogger/assets/137924470/d99c4e79-ccf7-45db-a3a2-73b337d191bd)
![image](https://github.com/jongpie/NebulaLogger/assets/137924470/06e458e4-2c62-4441-a296-a4a1c9484454)

**Comment by ryanwischnefski** [comment]
Someone smarter than me helped realize I need to toggle 'Save Log'. Sorry!

**Comment by jongpie** [comment]
@ryanwischnefski no worries, glad you were able to get it sorted out! If you have any other questions or issues, please let me know!
