### ISSUE TITLE
Add the ability to use Nebula Logger in OmniStudio

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#644]
Orgs using [OmniScript](https://help.salesforce.com/s/articleView?id=sf.os_omniscript_basics.htm&language=en_US&type=5) should have a way to leverage Nebula Logger. 

I've never worked with OmniScript before, so I'm not sure what all is involved with this - potentially, this might make sense to build as an optional plugin, instead of adding it directly to the core package.

**Comment by gpauriyal-github-unimelb** [comment]
@jongpie Did you have any luck with this? We plan to use a Custom Apex class that accepts the JSON from the IP and logs it in objects as needed.

**Comment by jongpie** [comment]
@gpauriyal-github-unimelb I have not looked into this anymore yet - since I don't have any experience with OmniScript or a personal use case for this functionality, it's a lower-priority item for me. If you're able to figure out any options for implementing this, let me know!

**Comment by jongpie** [comment]
Based on [this page](https://help.salesforce.com/s/articleView?id=sf.os_remote_action_for_integration_procedures_54037.htm&type=5) that @jamessimone found, it looks like there would need to be a call that implements the interface `System.Callable` to make it work in Omnistudio. I don't particularly like the `Callable` interface, so for now, I think the Omnistudio-related functionality should go into a new plugin package.

**Comment by jongpie** [comment]
OmniStudio logging is now provided out of the box in [release `v4.14.10`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.14.10) 🥳 . The wiki now also has [a page about logging in OmniStudio](https://github.com/jongpie/NebulaLogger/wiki/Logging-in-OmniStudio).
