### ISSUE TITLE
Log not created if flow call an Apex and logger set in the Apex

### ISSUE THREAD

**Issue by AndyHaoWu** [jongpie/NebulaLogger#663]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.8.2

### New Bug Summary

Notice if I have a flow and call an invocable apex within that flow, there are logger setup in the apex. When run the flow, and apex execute successfully, but logger not log in the log console. 
1. Tried to change save method to REST, platform event and queueable, neither work.
2. When run anonymous code in dev console, those logger been created(so no permission issue)

**Comment by AndyHaoWu** [comment]
Found the issue, i need to call the Logger.saveLog(); in the end...

**Comment by jongpie** [comment]
Glad you were able to sort it out - just let me know if you run into any other issues or questions!
