### ISSUE TITLE
Add emoji's for the log levels DEBUG, FINE, FINER and FINEST

### ISSUE THREAD

**Issue by twentyTwo** [jongpie/NebulaLogger#665]
### New Feature Summary
Emoji's are missing for the log level DEBUG, FINE, FINER, FINEST.
![image](https://github.com/jongpie/NebulaLogger/assets/4258676/82aedcc4-8d75-469e-8229-186454f58be5)

I'd like to add emoji's for the log level's that are missing. My proposed emoji's are

DEBUG - 🐞
FINE - 😊
FINER - 😄
FINEST - 😁

Let me know, if I can create a pull requests.

**Comment by jongpie** [comment]
Hi @twentyTwo, thanks for the feedback! I like the idea of using distinct emojis for DEBUG, FINE, FINER, and FINEST. From an accessibility perspective, I wonder if it would be better to use emojis for FINE, FINER, and FINEST that have different shapes - I worry that the 3 smiley emojis are too similar and it'll be hard to easily distinguish between them.

What do you think about using something like these options? They're visually distinct from one another, which would make it easier to notice the differences when looking through a long list of entries.
- DEBUG: 🐞
- FINE: 🎯
- FINER: 🌟
- FINEST: 🔍

I'm definitely open to other options too, but I'd like there to be some visual variety if possible.

**Comment by twentyTwo** [comment]
@jongpie

FINE:👍 
FINER:👌 
FINEST:🌟

There's a clear progression from "good" (Thumbs Up) to "better" (OK Hand) to "best" (Glowing Star), effectively conveying the intended meaning. The shapes are also different and can be easily distinguishable. What do you think?

**Comment by jongpie** [comment]
Ooooooh yeah, I love those options! The progression makes sense, and they're visually distinct.

If you're interested in submitting a PR for this change, feel free to do so & I can review - I'm also happy to make the changes later this week if you'd like, just let me know what you prefer.

**Comment by PawelWozniak** [comment]
Nice idea:
My proposition is:
INFO📢
ERROR⛔
WARN⚠️
DEBUG🐞
for FINE, FINER and FINEST I like the proposition of @twentyTwo

**Comment by jongpie** [comment]
@PawelWozniak thanks for the feedback! For INFO, I think the 📢 emoji might not be the best option - to me, that emoji indicates an announcement or that there's something urgent, which isn't really the case for an INFO log entry. Right now, INFO uses ✅ - I lean towards either keeping the existing emoji, or switching to something like ℹ️.

Let me know what you think!

**Comment by twentyTwo** [comment]
@jongpie , @PawelWozniak 
I think, ℹ️ is better suitable for INFO.

**Comment by jongpie** [comment]
These changes have been released in [`v4.13.9`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.13.9) 🥳
