### ISSUE TITLE
LWC Set Scenario not working

### ISSUE THREAD

**Issue by rcastanosgonzalez** [jongpie/NebulaLogger#666]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.13.6

### New Bug Summary

When adding a scenario to the log and calling saveLog(), the saveLog() method is not sending any scenario. It always arrives with the value null

**Comment by jongpie** [comment]
Fixed in in [release `v4.13.7`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.13.7) 🥳 🎉
