### ISSUE TITLE
Geeting error wile installing unlocked package in Production

### ISSUE THREAD

**Issue by sim9805** [jongpie/NebulaLogger#676]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.13.9

### New Bug Summary

Hi Team, 

Am continuously getting this error while installing unmanaged Nebula package in developer org.
Please advise how to fix this.
![image](https://github.com/jongpie/NebulaLogger/assets/101207881/1be64f35-2746-492b-9349-ba66474ab938)

Thanks.

**Comment by jamessimone** [comment]
@sim9805 that class is not part of the Nebula Logger package. There is an option when installing a package to only compile Apex classes that are part of the package - alternatively, if you do not use the `TrailLoopTest` class, you should consider deleting it from your org.

**Comment by jongpie** [comment]
Closing this out since this is an issue in the target org (not an issue with Nebula Logger). If you need anything else, let us know!
