### ISSUE TITLE
Log The Governor Limit Usage So Far And the Delta of the Limit Used from the last Instance of Logging the same

### ISSUE THREAD

**Issue by biswajith-s-pso-maxval** [jongpie/NebulaLogger#683]
### New Feature Summary

Expose a inner class in Nebula logger like "LimitsNotifier". It should have a single parameterized constructor like "public LimitsNotifier(String tagName)". If the class is called again and again from trigger with same tagName then we will have multiple instances of the class with the same tagName but a unique counter value that gets calculated inside the constructor.
Then we expose a method in nebula logger like "public void notice(String noticeId)". Upon calling it, it should create a snapshot of the limit that has been stored so far. Internally it will also capture the change in limits from the last instance of a similar snapshot taken with a different noticeId. If there is a change, then it should note it down. This will help is easily identifying at what point in code we consumed a governor limit and pinpoint to that location.
We should be able to configure which which limits we want the limitsNotifier instance to observe, and if that is not given, then it should pick that up from the default set of values defined in custom metadata types.
We should also be able be able to configure beyond how much consumption percentage of the governor limit, should the snapShot be marked with certain color (Like Low, Medium, High --> Green, Yellow, Red) and have certain Picklist value being set as well.

**A basic Apex class code for this without much of the discussed featues above is as follows:**

`public with sharing class LimitsNotifier {
    static Map<String, LimitsNotifier> classInstanceByUniqueInstance = new Map<String, LimitsNotifier>();
    static Map<String, Integer> counterByTagName = new Map<String, Integer>();
    String tagName;
    String uniqueInstanceName = '';

    Set<String> limitsBeingMonitored = new Set<String>{
        'soqlDelta',
        'dmlDelta'
    };

    static Map<String, List<LimitsSnapshot>> snapShotWithDeltaByTag = new Map<String, List<LimitsSnapshot>>();
    static Map<String, List<LimitsSnapshot>> snapShotWithDeltaByUniqueInstance = new Map<String, List<LimitsSnapshot>>();

    public LimitsNotifier(String tagName) {
        if(String.isBlank(tagName) || tagName == 'null'){
            throw new TagNameMissingException();
        }

        Integer counter = 0;
        if(counterByTagName.containsKey(tagName)){
            counter = counterByTagName.get(tagName);
        }
        counter++;
        counterByTagName.put(tagName, counter);

        this.tagName = tagName;
        uniqueInstanceName = tagName + ' <..> ' + String.valueOf(counter);

        LimitsSnapshot snapshot = new LimitsSnapshot();
        snapshot.uniqueInstanceName = this.uniqueInstanceName;
        snapshot.soql = Limits.getQueries();
        snapshot.dml = Limits.getDmlStatements();

        snapShotWithDeltaByUniqueInstance.put(this.uniqueInstanceName, new List<LimitsSnapshot>{snapshot});
        classInstanceByUniqueInstance.put(this.uniqueInstanceName, this);

        System.debug('~~~~ [Constructor] ' + uniqueInstanceName);
        System.debug('~~~~ [Constructor] SOQL: ' + snapshot.soql);
        System.debug('~~~~ [Constructor] DML: ' + snapshot.dml);
    }

    public void notice(String noticeId){
        snapByUniqueInstance(noticeId);
       // snapByTag(noticeId);
    }

    void snapByUniqueInstance(String noticeId){
        if(String.isBlank(noticeId) || noticeId == 'null'){
            throw new NoticeIdMissingException('In LimitsNotifier class the Notice Id is missing for instance : ' + this.uniqueInstanceName);
        }
        
        LimitsSnapshot snapshot = new LimitsSnapshot();
        snapshot.noticeId = noticeId;
        snapshot.uniqueInstanceName = this.uniqueInstanceName;
        snapshot.soql = Limits.getQueries();
        snapshot.dml = Limits.getDmlStatements();

        LimitsSnapshot previousSnapshot;

        List<LimitsSnapshot> snapshots = snapShotWithDeltaByUniqueInstance.get(this.uniqueInstanceName);
        previousSnapshot = snapshots[snapshots.size() - 1];

        snapshot.soqlDelta = snapshot.soql - previousSnapshot.soql;
        snapshot.dmlDelta = snapshot.dml - previousSnapshot.dml;

        Boolean needToTrack = false;
        
        if(
            limitsBeingMonitored.contains('soqlDelta')
            &&
            snapshot.soqlDelta > 0
        ){
            needToTrack = true;
        }

        if(
            limitsBeingMonitored.contains('dmlDelta')
            &&
            snapshot.dmlDelta > 0
        ){
            needToTrack = true;
        }

        if(needToTrack == true){
            snapShotWithDeltaByUniqueInstance.get(this.uniqueInstanceName).add(snapShot);
           
            System.debug('!!!! Delta : ' + uniqueInstanceName + ' .NoticeId : ' + noticeId);
            if(snapShot.soqlDelta > 0 && limitsBeingMonitored.contains('soqlDelta')){
                System.debug('!!!! SOQLs delta: ' + String.valueOf(snapShot.soqlDelta) + ' , SOQL so far: ' + String.valueOf(snapShot.soql));
            }
            if(snapshot.dmlDelta > 0 && limitsBeingMonitored.contains('dmlDelta')){
                System.debug('!!!! DMLs delta: ' + String.valueOf(snapShot.dmlDelta) + ' , DML so far: ' + String.valueOf(snapShot.dml));
            }
        }
    }

    public class LimitsSnapshot {
        public String noticeId;
        public String uniqueInstanceName;
        public Integer soql;
        public Integer dml;
        public Integer soqlDelta;
        public Integer dmlDelta;
    }

    @InvocableMethod
    public static List<Response> notifyAboutExceedingLimits(List<Request> requests){
        List<Response> responses = new List<Response>();

        LimitsNotifier l;
        if(requests[0].generateTag == true){
            l = new LimitsNotifier(requests[0].tagName);
        }

        if(requests[0].notice == true){
            if(
                LimitsNotifier.classInstanceByUniqueInstance.containsKey(requests[0].uniqueInstanceName)
            
            ){
                l = LimitsNotifier.classInstanceByUniqueInstance.get(requests[0].uniqueInstanceName);
                l.notice(requests[0].noticeId);
            }
            else{
                throw new UniqueInstanceNameMissingException();
            }
        }

        if(requests[0].publishResultForUniqueInstance == true){
            if(
                LimitsNotifier.classInstanceByUniqueInstance.containsKey(requests[0].uniqueInstanceName)
            
            ){
                l = LimitsNotifier.classInstanceByUniqueInstance.get(requests[0].uniqueInstanceName);
                l.publishResultForUniqueInstance();
            }
            else{
                throw new UniqueInstanceNameMissingException(
                    'Can not find any previous LimitsNotifier instance for the unique instance id: ' + requests[0].uniqueInstanceName
                );
            }
        }

        for(Request rr : requests){
            Response r = new Response();
            r.uniqueInstanceName = l.uniqueInstanceName;
            responses.add(r); 
        }

        return responses;
        

    }

    public class Request{
        @InvocableVariable
        public Boolean generateTag;
        @InvocableVariable
        public String tagName;
        @InvocableVariable
        public String uniqueInstanceName;
        @InvocableVariable
        public Boolean notice;
        @InvocableVariable
        public String noticeId;
        @InvocableVariable
        public Boolean publishResultForUniqueInstance;
    }

    public class Response{
        @InvocableVariable
        public String uniqueInstanceName;
    }

    public class NoticeIdMissingException extends Exception{

    }

    public class UniqueInstanceNameMissingException extends Exception{

    }

    public class TagNameMissingException extends Exception{

    }
}`

**Comment by jongpie** [comment]
Hi @biswajith-s-pso-maxval I'm struggling a bit to understand how this would be used, and what advantage this provides over Nebula Logger's current functionality (shown in the screenshot below). Currently:
- It already captures the usage of every transaction limit when a new log entry is created. These values show up in the tab "Transaction Limits" on each `LogEntry__c` record.
- Because each log entry has a snapshot of the transaction limits, you can look at log entries in the same log to identify at what point in the code/transaction you consumed a governor limit.
  - Admittedly, the current functionality in Nebula Logger does not calculate the delta of the limits usage between log entries for you. You would have to calculate the delta yourself. But having Nebula Logger calculate it in-memory would consume more CPU time & heap size, so it feels like something that should be handled via reporting.
- It already flags each limit with emojis based on the total usage of the limit.
  - ⛔- 90% or more of the limit has been consumed
  - ⚠️ - 80% to 90% of the limit has been consumed
  - ✅ - less than 80% of the limit has been consumed
- The existing functionality all currently happens simply by logging (e.g., calling `Logger.info('hello, world')`) - with your approach, I think there would be more work/responsibility needed by the org's code to call the `LimitsNotifier` class, as well as specifying which limits to track, and configuring new custom metadata type records.

  ![image](https://github.com/jongpie/NebulaLogger/assets/1267157/d2df8fc0-f5ce-43e9-921b-f8809914ea84)

Can you clarify how you envision your `LimitsNotifier` class being used, and how that differs from the current functionality?

**Comment by biswajith-s-pso-maxval** [comment]
Apologies @jongpie , I didn't know this feature existed. As I read through the Readme space of the repository I didn't see this.
I should have installed the package practically and tried it.
Please kindly close this request.
