### ISSUE TITLE
assertion failure for it_should_return_user_search_results_list_when_matches_found test method

### ISSUE THREAD

**Issue by heapallocation** [jongpie/NebulaLogger#688]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.12.9

### New Bug Summary

Hi there,

I have installed the unlocked pkg in a sandbox and am attempting to deploy via the metadata api. Upon deploying I get an assertion failure in the it_should_return_user_search_results_list_when_matches_found method of the LoggerEngineDataSelector_Tests.cls.

It is the second assertion: System.Assert.areEqual(expectedResultsById.size(), result.size()); the reason it fails is that the LogManagementDataSelector.getUsersByNameSearch soql query has a limit of 20, this invariable makes the expectedResultsById different to the users returned from the org for the results.size.

I have fixed the issue for myself, but just thought I'd raise an issue to let you guys know.

Cheers!
John.

**Comment by jongpie** [comment]
@heapallocation thanks for reporting this - this should hopefully be an easy fix. I'll try to get this resolved in the next few weeks/wherever I'm able to release a new version.
