### ISSUE TITLE
Make Log and Log Entry page tabs conditionally visible based on logged data

### ISSUE THREAD

**Issue by TrangOul** [jongpie/NebulaLogger#697]
### New Feature Summary

Finally the [required feature has been implemented (Summer '24)](https://ideas.salesforce.com/s/idea/a0B8W00000H6VzyUAF/allow-conditional-tabs-for-lightning-app-builder-tab-component).

Please make use of it and make the tabs conditionally visible:
![image](https://github.com/jongpie/NebulaLogger/assets/5629046/e4e6e05a-abbe-4eeb-a767-d4ab03116859)

**Comment by TrangOul** [comment]
Sure, let's wait until Summer'24 is fully released, so a premature update won't break anyone's org. Thank you!

**Comment by jongpie** [comment]
Hahahah yeah, not sure how many votes it helped contribute, but either way, glad to see that this feature is finally being delivered 🥳
