### ISSUE TITLE
Add the ability to capture headers for HttpRequest

### ISSUE THREAD

**Issue by pankaj0509** [jongpie/NebulaLogger#701]
### New Feature Summary

Hi Team,

I am trying to log callout log and i am able to see the log . It is working fine however I am seeing that there is no  request header being populated in "RestRequestHeaderKeys__c" in logEtry__c object . Could you please suggest me . it is a bug or there is no such feature to collect request header information.

Pankaj

**Comment by jongpie** [comment]
Hi @pankaj0509 - can you provide some more informaton on what you're logging? A sample of your code would be helpful.

**Comment by pankaj0509** [comment]
Hi @jongpie  Thanks for your reponse .

Actually I am using below code.

Logger.info(methodName).setHttpResponseDetails(httpResponse).setHttpRequestDetails(httpRequest)
                                    .setField( LogEntryEvent__e.Source_System__c, StringConstants.SALESFORCE_STRING)
                                    .setField( LogEntryEvent__e.Destination_System__c, httpRequest.getEndpoint())
                                    .setField( LogEntryEvent__e.Log_Type__c, StringConstants.OUTBOUND_RECORD_TYPE)
                                    .setField( LogEntryEvent__e.Method_Name__c, methodName)
                                    .setField(LogEntryEvent__e.Total_Callout_Duration__c, miliSecInInteger);

You can see that I am using setHttpRequestDetails(HttpRequest). Here HttpRequest is having various headers . 

        httpRequest.setHeader('involved-party-id-type', 'CIF');
        httpRequest.setHeader('involved-party-version', '7');
        httpRequest.setHeader('Content-Type', 'application/json');

once callout transaction is successful . I am getting log entries is generated as expected but when i see that request header information it is coming blank.

**Comment by pankaj0509** [comment]
@jongpie  Do you mean we have to create following fields in logEntryEvent__e and logEntry__c object .
HttpRequestHeaderKeys__c
HttpRequestHeaders__c

and then we have to overload setHttpRequestDetails(httpRequest, headersToLog).

need to create overload method in LogEntryEventBuilder  class

 global LogEntryEventBuilder setHttpRequestDetails(System.HttpRequest request, List<String> headerList) {
        if (this.shouldSave() == false || request == null) {
            return this;
        }

        String truncatedRequestBody = LoggerDataStore.truncateFieldValue(Schema.LogEntryEvent__e.HttpRequestBody__c, request.getBody());
        String cleanedRequestBody = applyDataMaskRules(this.userSettings.IsDataMaskingEnabled__c, truncatedRequestBody);
        Boolean requestBodyMasked = cleanedRequestBody != truncatedRequestBody;
		
		
		
        String formattedHeadersString;
        if (LoggerParameter.STORE_HTTP_REQUEST_HEADER_VALUES) {
            List<String> headers = new List<String>();
            for (String headerKey : headerList) {
                headers.add(String.format(HTTP_HEADER_FORMAT, new List<String>{ headerKey, request.getHeader(headerKey) }));
            }
            formattedHeadersString = String.join(headers, NEW_LINE_DELIMITER);
        }

        this.logEntryEvent.HttpRequestBody__c = cleanedRequestBody;
        this.logEntryEvent.HttpRequestBodyMasked__c = requestBodyMasked;
        this.logEntryEvent.HttpRequestCompressed__c = request.getCompressed();
        this.logEntryEvent.HttpRequestEndpoint__c = request.getEndpoint();
        this.logEntryEvent.HttpRequestMethod__c = request.getMethod();
	// Populating below newly created fields
		this.logEntryEvent.HttpRequestHeaderKeys__c = String.join(headerList, NEW_LINE_DELIMITER);
        this.logEntryEvent.HttpRequestHeaders__c = LoggerDataStore.truncateFieldValue(Schema.LogEntryEvent__e.HttpRequestHeaders__c, formattedHeadersString);
       
        return this;
    }

kindly advise if my understanding is correct

**Comment by jongpie** [comment]
@pankaj0509 yeah, your understanding is correct! And I think your sample code looks correct too. What do you think of this approach?

**Comment by jongpie** [comment]
This functionality is now available in [release `v4.14.8`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.14.8)

**Comment by TrangOul** [comment]
I wouldn't call it a complete solution, since the developer needs to manually list all the headers to be logged - some of which may be difficult to find, as they may be set elsewhere than in the code, for example in External Credentials. But it's the best we can have right now, unless Salesforce extends the `HttpRequest` API with `getHeaderKeys`, like in `HttpResponse`.
