### ISSUE TITLE
Excessive API Usage?

### ISSUE THREAD

**Issue by anthogiuliano** [jongpie/NebulaLogger#706]
Hi, I noticed some excessive API usage after starting to use logger. I found the LoggerParameter.CallStatusApi documented [here](https://github.com/jongpie/NebulaLogger/blob/main/docs/apex/Configuration/LoggerParameter.md) and it seems like the likely culprit. I can disable, but it'd be nice if we could do this status callout only on certain log levels like Warn or higher for example. My org is pretty sensitive to API usage.

If I'm using the EVENT_BUS saving method, are there any other settings I can look at to avoid a potentially high volume of API requests?

I'm using v4.13.11 of the Unlocked Package. Any info anyone could provide would be super helpful. Thanks in advance!

**Comment by anthogiuliano** [comment]
Just a quick question / update, I'm not sure if the uptick I noticed was entirely caused by logger. It may have been coincidental timing.

Even with LoggerParameter.CallStatusApi enabled, there shouldn't be more than one callout per LogEvent. Is that right?

**Comment by jongpie** [comment]
@anthogiuliano I think the uptick you're seeing is unrelated to Nebula Logger. The callout to the status API doesn't count towards your org's API limits - your org limit is only for inbound calls to your org's API endpoints, whereas the callout to the status API is an outbound call, and the endpoint isn't part of your org/shouldn't count towards your limit.

**Comment by anthogiuliano** [comment]
Oh duh. Thank you for the response, and for this amazing framework!

**Comment by jongpie** [comment]
@anthogiuliano no problem! If you have any other questions/need anything else, just let me know!
