### ISSUE TITLE
Support for before save record triggered flows

### ISSUE THREAD

**Issue by rdehleribm** [jongpie/NebulaLogger#708]
### New Feature Summary

Before save flows cannot invoke invocable apex, meaning Nebula logger can't be used in before save record triggered flows.  I'm not sure how that would manifest, but please add support for using Nebula logger in before save flows in some way.

**Comment by jongpie** [comment]
@rdehleribm while I would love for this to be available, this is something that has to be implemented by Salesforce. There's unfortunately no way to make this work without using Apex.
