### ISSUE TITLE
Update prettier config to use 2 spaces (instead of 4)

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#723]
Once upon a time, I liked using 4 spaces for indentation. But now, I used 2 spaces in pretty much all of my other codebases, except Nebula Logger.

This change shouldn't have any functional impact, but it will change nearly ever file in the repo, so this needs to be done when there aren't any other open PRs/work-in-progress:
- Update `.prettierrc` to use `"tabWidth": 2`
- Re-run `prettier` on all files in the repo

I'm not sure if it makes sense to create a release/package version just for this change, but.... maybe?

**Comment by jamessimone** [comment]
This is the best

**Comment by TrangOul** [comment]
Even better, use tabs. Each dev can set the desired tab size. And the resulting file size is slightly smaller.
