### ISSUE TITLE
Update Slack Plugin Documentation for Improved Named Credentials

### ISSUE THREAD

**Issue by kacrouse** [jongpie/NebulaLogger#745]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.13.17

### New Bug Summary

The improved Named Credentials require a few more setup steps for the Slack Plugin. I had to do a bit of troubleshooting to figure out why they weren't working when I thought they should be. Sharing my steps below!

1. **Create a new External Credential.** Go to the Named Credentials page in setup, click *New* under the External Credentials tab. Select `No Authentication` in the Authentication Protocol dropdown (I called mine `Slack Webhooks (No Auth)`).
2. **Create a Principle for the External Credential.** In the *Principals* section of the External Credential you just created, click *New*. Type in a parameter name (I called mine `All`)
3. **Create a Named Credential.** Go back to the main Named Credentials page and click *New* in the Named Credentials tab. Name your Named Credential, paste in your Slack webhook URL, and select the External Credential you just created.
5. **Grant the Platform Integration User access to the External Credential** (the non-obvious step...). Create a new permission set or use an existing one, go to the *External Credential Principal Access* section and grant access to the External Credential you created in step 1. Assign the permission set to the Platform Integration User (there are often multiple... I queried the CreatedById of a Log record to determine which one to assign to).

Happy to open a PR that updates the docs to include this info!

**Comment by jongpie** [comment]
@kacrouse this is a great idea! If you're open to creating a PR for adding this info (and possibly some supporting screenshots?) to the Slack README, I'd be happy to review it.
