### ISSUE TITLE
When using Logger.error() Entry Exception Type is blank and HasExceptionLogEntries__c is false

### ISSUE THREAD

**Issue by solo-1234** [jongpie/NebulaLogger#75]
Hey,

Thanks for an awesome tool!

I'm trying it out with Logger.error() to log that something went wrong, and on the entry, Entry Exception Type is blank, and the Log's Has Exception Log Entries is false.

Hope you can help with this - thanks!

**Comment by solo-1234** [comment]
Hi thanks for answering! 

I'm using this code:
Logger.error('string of message',sObjectVar);

I'm not passing any exceptions as parameters, should I be?

Thank you!

**Comment by jongpie** [comment]
@solo-1234 thanks for the info (and sorry for the late response)! That's confirmed exactly what I thought - some of the roll-ups were built in an older version of the tool, and I don't think they quite make sense anymore, given how the tool now works. The original logger tool was much simpler - it only logged "diagnostic" and "exception" entries, it didn't really track logging levels like it should have. But given how logger has involved, it now makes more sense to have roll-ups based on the logging levels (ERROR, WARN, INFO, etc). This is being handled in PR #76.

**Comment by solo-1234** [comment]
Works great! Thanks!!

**Comment by jongpie** [comment]
Glad to hear it! Let me know if you find any other issues!

**Comment by solo-1234** [comment]
will do!
