### ISSUE TITLE
Slack Plugin Message Formatting

### ISSUE THREAD

**Issue by kacrouse** [jongpie/NebulaLogger#764]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

v4.14.7, slack plugin v1.5.3

### New Bug Summary

The stack trace shown in slack messages logged by the slack plugin don't format properly because they are multi-line, but single backticks are used. See image below

<img width="479" alt="image" src="https://github.com/user-attachments/assets/06462fa9-2334-4f5e-837e-59bfbd10ff37">

I think I found the issue in the line below—the two criteria for `isShort` should be combined via AND rather than OR. I think anytime you have multiline text you'd want to use triple backticks rather than single.
https://github.com/jongpie/NebulaLogger/blob/ff06c254b780a75b47974037a79a479f3968e26e/nebula-logger/plugins/slack/plugin/slack/classes/SlackLoggerPlugin.cls#L278

With that change, the slack message looks like
<img width="499" alt="image" src="https://github.com/user-attachments/assets/f5cd8a3d-64c2-4ed3-9e86-cc61feca8f50">

Pretty small update, but happy to submit a PR if you agree with the change!

**Comment by jongpie** [comment]
@kacrouse thanks for reporting this! I think your change makes sense, it should be `&&` instead of `||`. I have another PR open right now (PR #765), so I can just include this one-line fix as part of that PR. I'm planning to merge it today or tomorrow - I'll include a new package version for Slack plugin in the release notes.

**Comment by kacrouse** [comment]
Amazing, thanks!

**Comment by jongpie** [comment]
@kacrouse this is now fixed - the new package version ID for the plugin is `04t5Y0000015oTTQAY`. It's also mentioned [the `v4.14.10` release notes](https://github.com/jongpie/NebulaLogger/releases/tag/v4.14.10).

Thanks again for your help!
