### ISSUE TITLE
Add status & priority fields

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#77]
Currently, there are no built-in status or priority fields for the `Log__c` object - these fields may not be needed on every project or environment, but currently, there's no way to know if someone has reviewed/analyzed a log. This can lead to multiple people reviewing the same log, not realizing that they're duplicating efforts. 

I often add these fields (or similar fields) on most projects anyway, so it'd be good to have this built in to the tool/included in the managed package.

**Comment by jamessimone** [comment]
This would be a great enhancement!
