### ISSUE TITLE
Aura/LWC stack trace parsing is not accurate when lightning debug mode is disabled

### ISSUE THREAD

**Issue by srikanth3107** [jongpie/NebulaLogger#776]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.14.12

### New Bug Summary

Hi @jongpie @ZackFra ,

I installed 4.14.12 version unlocked package , when i try to log for LWC ,the stack trace is not clear still the same issue persists for me what @ZackFra attached image ,i am using chrome .

This is the below code i am using

          <template>
            <c-logger></c-logger>
            <div>Nebule Logger Component</div>
            <lightning-button variant="base" label="click To Log" title="" onclick={log} class="slds-m-left_x-small">      
            </lightning-button>
           </template>
JS
log() {

    const logger = this.template.querySelector('c-logger');
    
     logger.error('ERROR!!!').addTag('TAG');
    
    logger.warn('WARN!!!');
    
    logger.info('INFO!!!');
    
    logger.debug('DEBUG!!!');
    
    logger.fine('FINE!!!');
    
    logger.finer('FINER!!!');
    
    logger.finest('FINEST!!!');
    
    logger.saveLog();
    
    }
Can you please help us with that

**Comment by srikanth3107** [comment]
![nebulla error](https://github.com/user-attachments/assets/cb4980b9-cfce-45ff-87f5-4de76070419a)

**Comment by jongpie** [comment]
@srikanth3107 I think I see what the issue is - it seems to be related to whether or not you have `lightning debug mode` enabled for your user. Can you check a few things in your org to help validate this?
- In your org, for your user, verify that lightning debug mode is _not_ enabled
- In your org, enable lightning debug, and see if the stack traces/origin fields are correct
  - You can enable/disable lightning debug in your org under `Setup --> Lightning Components --> Debug Mode`
        
    ![image](https://github.com/user-attachments/assets/8c0f666f-978a-4a64-8c5c-19452deff0d2)

**Comment by jongpie** [comment]
Thanks @srikanth3107. I'm re-opening the issue for now, this is still a bug - having lightning debug mode enabled shouldn't be required to get accurate stack traces. I have a fix for the issue, it'll be included in PR #775.

**Comment by jongpie** [comment]
@srikanth3107 this is now fixed in [release v4.14.13](https://github.com/jongpie/NebulaLogger/releases/tag/v4.14.13) - Aura & LWC stack traces should now be accurate with lightning debug mode is enabled or disabled.

Thanks again for reporting this!
