### ISSUE TITLE
Deploy to directly Production crashing

### ISSUE THREAD

**Issue by marcellcsiszar** [jongpie/NebulaLogger#8]
I tried to deploy your package directly into our org but a few test are failing at the moment for us:

`Deployment CompleteTest failure, method: LogglyLogPushScheduler_Tests.it_should_schedule_the_batch_job -- System.AssertException: Assertion Failed: Expected: 0, Actual: 23 stack Class.LogglyLogPushScheduler_Tests.it_should_schedule_the_batch_job: line 12, column 1

Test failure, method: LogglyLogPushScheduler_Tests.it_should_schedule_the_batch_job_schedule_hourly -- System.AssertException: Assertion Failed: Expected: 0, Actual: 23 stack Class.LogglyLogPushScheduler_Tests.it_should_schedule_the_batch_job_schedule_hourly: line 35, column 1

Test failure, method: LogglyLogPushScheduler_Tests.it_should_schedule_the_batch_job_schedule_every_5_minutes -- System.AssertException: Assertion Failed: Expected: 0, Actual: 23 stack Class.LogglyLogPushScheduler_Tests.it_should_schedule_the_batch_job_schedule_every_5_minutes: line 25, column 1

Test failure, method: SlackLogPushScheduler_Tests.it_should_schedule_the_batch_job_schedule_hourly -- System.AssertException: Assertion Failed: Expected: 0, Actual: 23 stack Class.SlackLogPushScheduler_Tests.it_should_schedule_the_batch_job_schedule_hourly: line 35, column 1

Test failure, method: SlackLogPushScheduler_Tests.it_should_schedule_the_batch_job_schedule_every_5_minutes -- System.AssertException: Assertion Failed: Expected: 0, Actual: 23 stack Class.SlackLogPushScheduler_Tests.it_should_schedule_the_batch_job_schedule_every_5_minutes: line 25, column 1

Test failure, method: SlackLogPushScheduler_Tests.it_should_schedule_the_batch_job -- System.AssertException: Assertion Failed: Expected: 0, Actual: 23 stack Class.SlackLogPushScheduler_Tests.it_should_schedule_the_batch_job: line 12, column 1

Test failure, method: TrelloLogPushScheduler_Tests.it_should_schedule_the_batch_job -- System.AssertException: Assertion Failed: Expected: 0, Actual: 23 stack Class.TrelloLogPushScheduler_Tests.it_should_schedule_the_batch_job: line 12, column 1

Test failure, method: TrelloLogPushScheduler_Tests.it_should_schedule_the_batch_job_schedule_every_5_minutes -- System.AssertException: Assertion Failed: Expected: 0, Actual: 23 stack Class.TrelloLogPushScheduler_Tests.it_should_schedule_the_batch_job_schedule_every_5_minutes: line 25, column 1

Test failure, method: TrelloLogPushScheduler_Tests.it_should_schedule_the_batch_job_schedule_hourly -- System.AssertException: Assertion Failed: Expected: 0, Actual: 23 stack Class.TrelloLogPushScheduler_Tests.it_should_schedule_the_batch_job_schedule_hourly: line 35, column 1
`
I've checked those test files and I think there are some areas for improvement :)
I'm not sure if anyone else is getting these errors, but the tests should look differently, example: asserting after testing, not just before the test, etc.. :)

**Comment by jongpie** [comment]
Hi @marcellcsiszar - thanks for reporting these issues! I definitely need to improve the unit tests - I hope to have some time next week to work on them. I'll update this page as soon as I have some changes.

In the meantime, if you find any other issues, let me know!

**Comment by jongpie** [comment]
@marcellcsiszar this should now be fixed - I release a small patch, [v0.12.1-beta](https://github.com/jongpie/NebulaLogger/releases/tag/v0.12.1-beta). 

Please let me know if you have any more issues or feedback!

**Comment by marcellcsiszar** [comment]
Thanks for the fix. I have deployed this pckg now without any issues.

**Comment by jongpie** [comment]
Fantastic, thanks for the update!
