### ISSUE TITLE
Add a custom component to show related logs on an SObject's flexipage

### ISSUE THREAD

**Issue by jongpie** [jongpie/NebulaLogger#80]
With the current implementation, `LogEntry__c` records are "related" to SObject records by storing the record ID in the text field `LogEntry__c.RecordId__c` - as far as Salesforce is concerned, there is no true relationship (lookup field) that relates `LogEntry__c` to another SObject. This means that log entries for a specific record cannot be added to a page layout using standard related lists.

One workaround for this is to add lookups on `LogEntry__c` for each desired SObject and populate the appropriate lookup with the value of `LogEntry__c.RecordId__c` (and then leverage standard related lists), but it's not a scalable approach & can't be provided by this repo. Instead, another workaround is needed - create a Lightning web component that can be added to an object's flexipage (e.g., add it to the flexipage for Account, Lead, Opportunity, etc.) and display any `LogEntry__c` objects where `LogEntry__c.RecordId__c == <recordId>`

- The component should look like & behave like a standard related list (including column sorting, resizing, responsive design/mobile friendly, etc.)
- The columns displayed should be configurable via field sets on `LogEntry__c`
- Within App Builder, admins should be able to specify the name of the desired field set to use
- Within App Builder, admins should be able to specify the number of rows to display by default, as well as which column(s) to sort on by default
- The component should honor object security, field-level security & record access security - including hiding the component itself if the user does not have access to `Log__c` or `LogEntry__c`

**Comment by solo-1234** [comment]
I've been using lwc-utils soqldatatable to show related log entries on any record page. I just noticed that it stopped working since RelatedRecordId isn't populated on new log entries. Has that field been deprecated?

Would it help if my apex assigned a record id in addition to the whole record?

I've used that field when logging multiple entries for one record, and I don't want to store the entire record for each entry.

**Comment by jongpie** [comment]
Hey @solo-1234! That's great to know about lwc-utils' soqldatatable, I'll check it out to see if I can incorporate it (instead of building a custom component from scratch).

Regarding your query, it looks like you still have some old fields in your org - the `RelatedRecordId__c` field was deprecated & replaced a few months ago with another field just called `RecordId__c` - check your org to see if the new `RecordId__c` field is present & being populated.

Here is the full list of record fields currently used by the package - you should keep these fields, and delete any similar fields on `LogEntry__c` that have the "Related" prefix (delete `RelatedRecordId__c`, `RelatedRecordName__c`, etc.). 

![image](https://user-images.githubusercontent.com/1267157/106638988-547dbd80-6539-11eb-9ecb-e8916c2956ae.png)

**Comment by solo-1234** [comment]
Ohh that explains it! The RecordId field on my entry is populated, so I'll just modify the SOQL in the datatable to reference that field.

Thanks for the heads up about those deprecated fields! I'll delete them so I don't make that mistake again.

**Comment by jongpie** [comment]
Awesome, glad that explains it! Let me know if you run into any other issues!

**Comment by solo-1234** [comment]
Before I delete, I just wanted to confirm - are all of these fields deprecated?
`HasRelatedRecordId__c
HasRecordId__c
HasRecordJson__c
RelatedRecordDetailedLink__c
RelatedRecordLink__c
RelatedRecordId__c
RelatedRecordJson__c
RecordJson__c
RelatedRecordName__c
RelatedRecordSObject__c
`
Thanks!

**Comment by jongpie** [comment]
@solo-1234 that list isn't quite right, it includes a few fields that you should keep (and apologies, I forgot to include a few fields to keep in my last comment). Here's the cleaned up list of fields to delete
- `HasRelatedRecordId__c`
- `RelatedRecordDetailedLink__c`
- `RelatedRecordLink__c`
- `RelatedRecordId__c`
- `RelatedRecordJson__c`
- `RelatedRecordName__c`
- `RelatedRecordSObject__c`

Your original list also included `HasRecordId__c`, `HasRecordJson__c`, `RecordJson__c` - you should keep these 3 fields (and you'll get errors if you try to delete them because they're currently referenced in Apex code). Let me know if you need anything else!

**Comment by solo-1234** [comment]
Got it, thanks again!

**Comment by solo-1234** [comment]
I wasn't able to delete `HasRelatedRecordId__c` since it's referenced in `TotalLogEntriesWithRelatedRecordId__c`, is that field also deprecated?

Thanks!

**Comment by jongpie** [comment]
@solo-1234 yeah, that rollup field was removed as well - I just remembered that I documented the list of deleted fields in [the 3.2.0-beta release notes](https://github.com/jongpie/NebulaLogger/releases/tag/v3.2.0-beta). I _think_ it has the full list of deleted fields, but let me know if you run into any other issues!
