### ISSUE TITLE
Add setDatabaseResult(EmptyRecycleBinResult) and setDatabaseResult(List<EmptyRecycleBinResult>)

### ISSUE THREAD

**Issue by TrangOul** [jongpie/NebulaLogger#804]
### New Feature Summary

Just for the sake of completeness, please add [`setDatabaseResult(EmptyRecycleBinResult)` and `setDatabaseResult(List<EmptyRecycleBinResult>)`](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database_EmptyRecycleBinResult.htm) methods (for results of [`Database.emptyRecycleBin`](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_database.htm)), so we can log all `Database....Result` objects.

**Comment by jongpie** [comment]
This is now available in [release `v4.15.2`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.15.2) 🥳
