### ISSUE TITLE
Stack Trace is not working in LWC when we  are logging

### ISSUE THREAD

**Issue by srikanth3107** [jongpie/NebulaLogger#820]
### Package Edition of Nebula Logger

Unlocked Package

### Package Version of Nebula Logger

4.14.13

### New Bug Summary

@jongpie @jamessimone 
I have already raised the same issue #776 , at that time in version 4.14.13 it was fixed , but now in same version i am facing the issue same again 
This is just the test code i wrote , can you please look into this please let me know if you want any other details

import { LightningElement } from 'lwc';
import { getLogger } from 'c/logger';

export default class TestNebulla extends LightningElement {
    logger = getLogger();

   connectedCallback() {
    this.logger.error('Testing Record');
    this.logger.saveLog();
  }
}

![image](https://github.com/user-attachments/assets/c093f63f-875b-4cc9-baca-7821b2e5221f)

**Comment by jongpie** [comment]
Hi @srikanth3107 - could you clarify what part isn't working? Based on the screenshot you provided, the stack trace looks correct to me - the first line mentions the `connectedCallback` function from within `c/testNebula.js`.

**Comment by srikanth3107** [comment]
@jongpie we will not get the snapshot of this in LWC , how we are getting in apex the exact snapshot

**Comment by jongpie** [comment]
@srikanth3107 just to clarify, are you referring to [the Apex code snppets that were introduced in `v4.13.1`](https://github.com/jongpie/NebulaLogger/releases/tag/v4.13.1)? If so, then that is expected behavior - code snippets are currently only supported for Apex code, it does not work (and never has) for LWC/Aura components.

**Comment by srikanth3107** [comment]
Sorry for the confusion , Thanks for the confirmation
